CREATE TABLE DBLOCALIDADE.TB_DISTRITO_SVS  (
   CO_DISTRITO          VARCHAR(9)                      NOT NULL
      CONSTRAINT NN_DISTRITO_CODISTRITO CHECK (CO_DISTRITO IS NOT NULL),
   NO_DISTRITO          VARCHAR(50),
   CO_MUNICIPIO_IBGE    VARCHAR(6),
   CO_SISTEMA           NUMERIC(8)                      
      CONSTRAINT CKC_CO_SISTEMA_TB_DISTR CHECK (CO_SISTEMA IS NULL OR (CO_SISTEMA IS NOT NULL)),
   ST_REGISTRO_ATIVO    VARCHAR(1),
   CONSTRAINT PK_DISTRITO_SVS PRIMARY KEY (CO_DISTRITO),
   CONSTRAINT NN_DISTRITOSVS_CODISTRITO CHECK (CO_DISTRITO IS NOT NULL)
);

COMMENT ON TABLE DBLOCALIDADE.TB_DISTRITO_SVS IS
'Contém informações sobre distritos sanitários';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_DISTRITO IS
'Código IBGE do Distrito Sanitário';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.NO_DISTRITO IS
'Nome do Distrito Sanitário';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_MUNICIPIO_IBGE IS
'Código IBGE do Município';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_SISTEMA IS
'Código Sequencial do Sistema';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.ST_REGISTRO_ATIVO IS
'Indica se o registro está ativo';


CREATE TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO  (
   CO_ESTABELECIMENTO   NUMERIC(8,0)                     NOT NULL
      CONSTRAINT CKC_CO_ESTABELECIMENT_RL_ESTAB CHECK (CO_ESTABELECIMENTO IS NOT NULL),
   CO_MUNICIPIO_IBGE    VARCHAR(6)                     NOT NULL
      CONSTRAINT CKC_CO_MUNICIPIO_IBGE_RL_ESTAB CHECK (CO_MUNICIPIO_IBGE IS NOT NULL),
   CO_DISTRITO          VARCHAR(9)                      NOT NULL,
   CO_SISTEMA           NUMERIC(8)                      NOT NULL,
   CONSTRAINT PK_ESTAB_SAUDE_DISTRITO PRIMARY KEY (CO_ESTABELECIMENTO, CO_MUNICIPIO_IBGE, CO_DISTRITO, CO_SISTEMA)
);

COMMENT ON TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO IS
'RL_ESTAB_SAUDE_DISTRITO';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_ESTABELECIMENTO IS
'Código do Estabelecimento de Saúde';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_MUNICIPIO_IBGE IS
'Código do Município IBGE';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_DISTRITO IS
'Código IBGE do Distrito';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_SISTEMA IS
'Código do Sistema';