COMMENT ON COLUMN DBSINAN.TB_INVESTIGA_DENGUE.DT_COLETA_NS1  IS 'DATA DA COLETA DO EXAME NS1 ONDE NS1 É UMA PROTEÍNA NÃO ESTRUTURAL DO VÍRUS DA DENGUE';
COMMENT ON COLUMN DBSINAN.TB_INVESTIGA_DENGUE.TP_RESULTADO_NS1  IS 'POSSÍVEIS RESULTADOS DO EXAME PARA NS1 ONDE NS1 É UMA PROTEÍNA NÃO ESTRUTURAL DO VÍRUS DA DENGUE.1-Reagente 2-Não Reagente 3-Inconclusivo e 4-Não realizado';
COMMENT ON COLUMN DBSINAN.TB_NOTIFICACAO.TP_SISTEMA IS 'CAMPO QUE IDENTIFICA SE O USUÁRIO ESTÁ ACESSANDO O SITEMA: 1- LOCAL; 2- WEB';
ALTER TABLE dbsinan.TB_NOTIFICACAO_EPIZOOTIA ADD COLUMN TP_SISTEMA VARCHAR(1) DEFAULT '1';
ALTER TABLE dbsinan.TB_NOTIFICACAO_EPIZOOTIA ALTER COLUMN TP_SISTEMA DROP DEFAULT;
COMMENT ON COLUMN DBSINAN.TB_NOTIFICACAO_EPIZOOTIA.TP_SISTEMA IS 'CAMPO QUE IDENTIFICA SE O USUÁRIO ESTÁ ACESSANDO O SITEMA: 1- LOCAL; 2- WEB';
COMMENT ON COLUMN DBSINAN.TB_NOTIFICACAO.TP_FLUXO_RETORNO IS 'Identifica se o registro está habilitado para ser enviado no fluxo de retorno 0 - Não Liberado 1 - Habilitado para Fluxo de Retorno de município. 2 - Nível nacional gerou arquivo fluxo de retorno para o município. 3 - Habilitado para Fluxo de Retorno de distrito. 4 - Nível municipal gerou arquivo fluxo de retorno para o distrito. 5 - Registro que foi excluído do fluxo de retorno na base única.'; 
update dbsinan.tb_agravo set tp_esfera_notificacao = '1' where co_cid = 'A08.0';
update dbsinan.tb_agravo set tp_esfera_notificacao = '1' where co_cid = 'W64';
update dbsinan.tb_agravo set tp_esfera_notificacao = '1' where co_cid = 'X29';
update dbsinan.tb_agravo set no_executavel = 'CONCLUSAO' , tp_esfera_notificacao = '1' , st_surto_agregado = 'N' , nu_prazo_encerramento = '60' ,tp_agravo = '1' , tp_calcula_prazo_encerramento = '1', tp_vinculo_agravo = '0' where co_cid = 'A53.9';
update dbsinan.tb_agravo set no_executavel = 'CONCLUSAO' , tp_esfera_notificacao = '1' , st_surto_agregado = 'N' , nu_prazo_encerramento = '60' ,tp_agravo = '1' , tp_calcula_prazo_encerramento = '1', tp_vinculo_agravo = '0' where co_cid = 'O98.6';
update dbsinan.tb_agravo set no_executavel = 'CONCLUSAO' , tp_esfera_notificacao = '1' , st_surto_agregado = 'N' , nu_prazo_encerramento = '60' ,tp_agravo = '1' , tp_calcula_prazo_encerramento = '1', tp_vinculo_agravo = '0' where co_cid = 'P37.1';
update dbsinan.tb_agravo set no_executavel = 'CONCLUSAO' , tp_esfera_notificacao = '1' , st_surto_agregado = 'N' , nu_prazo_encerramento = '60' ,tp_agravo = '1' , tp_calcula_prazo_encerramento = '1', tp_vinculo_agravo = '0' where co_cid = 'R36';
update dbsinan.tb_agravo set no_executavel = 'CONCLUSAO' , tp_esfera_notificacao = '1' , st_surto_agregado = 'N' , nu_prazo_encerramento = '60' ,tp_agravo = '1' , tp_calcula_prazo_encerramento = '1', tp_vinculo_agravo = '0' where co_cid = 'J18.9';
update dbsinan.tb_agravo set no_agravo = 'NEOPLASIA MALIGNA DO SISTEMA NERVOSO CENTRAL, NAO ESPECIFICADA' WHERE co_cid = 'C72.9';
ALTER TABLE dbsinan.tb_notificacao_negativa ADD COLUMN dt_digitacao date;
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_pcr_escarro varchar(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_pop_liberdade character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_pop_rua character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_pop_saude character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_pop_imigrante character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_benef_gov character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN st_agravo_drogas character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN st_agravo_tabaco character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_molecular character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_sensibilidade character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN nu_contato_identificados numeric(2,0);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_antirretroviral_trat character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN st_bacil_apos_6_mes character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN nu_prontuario_atual character varying(10);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN tp_transf character varying(1);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN co_uf_transf character varying(2);
ALTER TABLE dbsinan.tb_investiga_tuberculose ADD COLUMN co_municipio_transf character varying(6);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN tp_orientacao_sexual character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN tp_identidade_genero character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN tp_violencia_motivada character varying(2);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN Tp_ciclo_de_vida_autor character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_rede_saude character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_assistencia_social character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_rede_de_educacao character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_rede_atendimento_mulher character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_conselho_tutelar character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_conselho_idoso character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_del_atendi_idoso character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_centro_ref_direitos_humanos character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_mp character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_del_prot_crianca_adolescente character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_del_atendimento_mulher character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_outra_delegacia character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_justica_infancia_juventude character varying(1);
ALTER TABLE dbsinan.tb_investiga_violencia_dom ADD COLUMN st_defensoria_publica character varying(1);