CREATE OR REPLACE FUNCTION itoa(integer) 
RETURNS TEXT AS 
$$
  SELECT CAST(CAST($1 AS INT8) AS TEXT);
$$ LANGUAGE SQL;

CREATE CAST (INTEGER AS TEXT) WITH FUNCTION itoa(integer) AS IMPLICIT;


CREATE OR REPLACE FUNCTION nutoa(NUMERIC) 
RETURNS TEXT AS 
$$
  SELECT CAST(CAST($1 AS double precision) AS TEXT);
$$ LANGUAGE SQL;

CREATE CAST (NUMERIC AS TEXT) WITH FUNCTION nutoa(NUMERIC) AS IMPLICIT;