INSERT INTO dbgeral.tb_regional_saude
VALUES
('1100','11','1100','MUNICIPIO IGNORADO - RO','Município ignorado - RO','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1101','11','1190','I DELEGACIA REGIONAL DE SAUDE','I DRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1102','11','1190','II DELEGACIA REGIONAL DE SAUDE','II DRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1103','11','1190','III DELEGACIA REG. DE SAUDE','III DRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1104','11','1190','DEPARTAMENTO DE EPIDEMIOLOGIA','Dept.Epidemiologia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1200','12','1200','MUNICIPIO IGNORADO - AC','Município ignorado - AC','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1201','12','1290','ACRE','Acre','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1202','12','1290','BRASILEIA','Brasiléia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1203','12','1290','CRUZEIRO DO SUL','Cruzeiro do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1300','13','1300','MUNICIPIO IGNORADO - AM','Município ignorado - AM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1301','13','1390','DIRES 1','DIRES 1','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1302','13','1390','DIRES 2','DIRES 2','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1303','13','1390','DIRES 3','DIRES 3','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1304','13','1390','DIRES 4','DIRES 4','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1305','13','1390','DIRES 5','DIRES 5','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1306','13','1390','DIRES 6','DIRES 6','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1307','13','1390','DIRES 7','DIRES 7','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1308','13','1390','DIRES 8','DIRES 8','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1309','13','1390','DIRES 9','DIRES 9','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1310','13','1390','DIRES 10','DIRES 10','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1400','14','1400','MUNICIPIO IGNORADO - RR','Município ignorado - RR','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1401','14','1490','SECRETARIA ESTADUAL DE SAUDE','SES - RR','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1500','15','1500','MUNICIPIO IGNORADO - PA','Município ignorado - PA','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1501','15','1590','I REGIONAL DE SAUDE','I RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1502','15','1590','II REGIONAL DE SAUDE','II RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1503','15','1590','III REGIONAL DE SAUDE','III RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1504','15','1590','IV REGIONAL DE SAUDE','IV RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1505','15','1590','V REGIONAL DE SAUDE','V RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1506','15','1590','VI REGIONAL DE SAUDE','VI RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1507','15','1590','VII REGIONAL DE SAUDE','VII RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1508','15','1590','VIII REGIONAL DE SAUDE','VIII RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1509','15','1590','IX REGIONAL DE SAUDE','IX RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1510','15','1590','X REGIONAL DE SAUDE','X RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1511','15','1590','XI REGIONAL DE SAUDE','XI RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1512','15','1590','XII REGIONAL DE SAUDE','XII RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1513','15','1590','XIII REGIONAL DE SAUDE','XIII RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1600','16','1600','MUNICIPIO IGNORADO - AP','Município ignorado - AP','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1601','16','1690','I REGIONAL DE SAUDE','I RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1602','16','1690','II REGIONAL DE SAUDE','II RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1700','17','1700','MUNICIPIO IGNORADO - TO','Município ignorado - TO','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1701','17','1790','PALMAS','Palmas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1702','17','1790','CULTURA DO CERRADO','Cultura do Cerrado','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1703','17','1790','MIRACEMA','Miracema','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1704','17','1790','SAO VALERIO PEIXE','São Valério Peixe','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1705','17','1790','PORTO NACIONAL','Porto Nacional','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1706','17','1790','PARAISO','Paraíso','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1707','17','1790','GUARAI','Guaraí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1708','17','1790','COLINAS','Colinas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1709','17','1790','GURUPI','Gurupi','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1710','17','1790','ARAGUAINA','Araguaína','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1711','17','1790','MEDIO ARAGUAIA','Médio Araguaia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1712','17','1790','TOCANTINOPOLIS','Tocantinópolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1713','17','1790','AUGUSTINOPOLIS','Augustinópolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1714','17','1790','SUDESTE','Sudeste','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('1715','17','1790','EXTREMO SUDESTE','Extremo Sudeste','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2100','21','2100','MUNICIPIO IGNORADO - MA','Município ignorado - MA','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2101','21','2190','BAIXADA MARANHENSE','Baixada Maranhense','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2102','21','2190','CHAPADA DAS MESAS','Chapada das Mesas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2103','21','2190','ILHA DO MARANHAO','Ilha do Maranhão','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2104','21','2190','PRE-AMAZONIA','Pré-Amazônia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2105','21','2190','SERRAS','Serras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2106','21','2190','ALPERCATAS','Alpercatas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2107','21','2190','ALTO MUNIM','Alto Munim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2108','21','2190','ALTO TURI','Alto Turi','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2109','21','2190','BAIXO BALSAS','Baixo Balsas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2110','21','2190','BAIXO ITAPECURU','Baixo Itapecuru','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2111','21','2190','BAIXO MUNIM','Baixo Munim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2112','21','2190','BAIXO TURI','Baixo Turi','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2113','21','2190','DELTA DO PARNAIBA','Delta do Parnaíba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2114','21','2190','FLORES','Flores','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2115','21','2190','GURUPI','Gurupi','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2116','21','2190','LITORAL OCIDENTAL','Litoral Ocidental','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2117','21','2190','MEARIM','Mearim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2118','21','2190','MEDIO MEARIM','Médio Mearim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2119','21','2190','MEDIO PARNAIBA','Médio Parnaíba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2120','21','2190','PERICUMA','Pericumã','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2121','21','2190','PINDARE','Pindaré','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2122','21','2190','SERTAO MARANHENSE','Sertão Maranhense','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2123','21','2190','TOCANTINS','Tocantins','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2124','21','2190','CARAJAS','Carajás','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2125','21','2190','COCAIS','Cocais','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2126','21','2190','EIXOS RODO-FERROVIARIOS','Eixos Rodo-Ferroviários','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2127','21','2190','GERAIS DE BALSAS','Gerais de Balsas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2128','21','2190','GUAJAJARAS','Guajajaras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2129','21','2190','IMIGRANTES','Imigrantes','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2130','21','2190','LAGOS','Lagos','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2131','21','2190','LENCOIS MARANHENSES','Lençóis Maranhenses','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2132','21','2190','TIMBIRAS','Timbiras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2200','22','2200','MUNICIPIO IGNORADO - PI','Município ignorado - PI','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2201','22','2290','PARNAIBA','Parnaíba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2202','22','2290','BARRAS','Barras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2203','22','2290','PIRIPIRI','Piripiri','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2204','22','2290','TERESINA','Teresina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2205','22','2290','CAMPO MAIOR','Campo Maior','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2206','22','2290','AMARANTE','Amarante','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2207','22','2290','VALENCA','Valença','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2208','22','2290','OEIRAS','Oeiras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2209','22','2290','PICOS','Picos','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2210','22','2290','FLORIANO','Floriano','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2211','22','2290','SAO JOAO DO PIAUI','São João do Piauí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2212','22','2290','SAO RAIMUNDO NONATO','São Raimundo Nonato','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2213','22','2290','BOM JESUS','Bom Jesus','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2214','22','2290','CORRENTE','Corrente','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2215','22','2290','URUCUI','Urucuí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2216','22','2290','FRONTEIRAS','Fronteiras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2217','22','2290','PAULISTANA','Paulistana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2300','23','2300','MUNICIPIO IGNORADO - CE','Município ignorado - CE','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2301','23','2301','FORTALEZA','Fortaleza','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2302','23','2301','CAUCAIA','Caucaia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2303','23','2301','MARACANAU','Maracanaú','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2304','23','2301','BATURITE','Baturité','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2305','23','2301','CANINDE','Canindé','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2306','23','2301','ITAPIPOCA','Itapipoca','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2307','23','2301','ARACATI','Aracati','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2308','23','2301','QUIXADA','Quixadá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2309','23','2301','RUSSAS','Russas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2310','23','2301','LIMOEIRO DO NORTE','Limoeiro do Norte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2311','23','2302','SOBRAL','Sobral','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2312','23','2302','ACARAU','Acaraú','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2313','23','2302','TIANGUA','Tianguá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2314','23','2301','TAUA','Tauá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2315','23','2302','CRATEUS','Crateús','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2316','23','2302','CAMOCIM','Camocim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2317','23','2301','ICO','Icó','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2318','23','2301','IGUATI','Iguatu','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2319','23','2303','BREJO SANTO','Brejo Santo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2320','23','2303','CRATO','Crato','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2321','23','2303','JUAZEIRO DO NORTE','Juazeiro do Norte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2400','24','2400','MUNICIPIO IGNORADO - RN','Município ignorado - RN','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2401','24','2490','I ETAM','I ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2402','24','2490','II ETAM','II ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2403','24','2490','III ETAM','III ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2404','24','2490','IV ETAM','IV ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2405','24','2490','V ETAM','V ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2406','24','2490','VI ETAM','VI ETAM','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2407','24','2490','GRANDE NATAL','Grande Natal','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2500','25','2500','MUNICIPIO IGNORADO - PB','Município ignorado - PB','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2501','25','2590','I NUCLEO REGIONAL DE SAUDE','I NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2502','25','2590','II NUCLEO REGIONAL DE SAUDE','II NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2503','25','2590','III NUCLEO REGIONAL DE SAUDE','III NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2504','25','2590','IV NUCLEO REGIONAL DE SAUDE','IV NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2505','25','2590','V NUCLEO REGIONAL DE SAUDE','V NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2506','25','2590','VI NUCLEO REGIONAL DE SAUDE','VI NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2507','25','2590','VII NUCLEO REGIONAL DE SAUDE','VII NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2508','25','2590','VIII NUCLEO REGIONAL DE SAUDE','VIII NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2509','25','2590','IX NUCLEO REGIONAL DE SAUDE','IX NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2510','25','2590','X NUCLEO REGIONAL DE SAUDE','X NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2511','25','2590','XI NUCLEO REGIONAL DE SAUDE','XI NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2512','25','2590','XII NUCLEO REGIONAL DE SAUDE','XII NRS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2600','26','2600','MUNICIPIO IGNORADO - PE','Município ignorado - PE','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2601','26','2690','I GERES - RECIFE','Recife','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2602','26','2690','II GERES - LIMOEIRO','Limoeiro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2603','26','2690','III GERES - PALMARES','Palmares','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2604','26','2690','IV GERES - CARUARU','Caruaru','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2605','26','2690','V GERES - GARANHUNS','Garanhuns','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2606','26','2690','VI GERES - ARCOVERDE','Arcoverde','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2607','26','2690','VII GERES - SALGUEIRO','Salgueiro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2608','26','2690','VIII GERES - PETROLINA','Petrolina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2609','26','2690','IX  GERES - OURICURI','Ouricuri','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2610','26','2690','X GERES - AFOGADOS DA INGAZEIRA','Afogados da Ingazeira','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2611','26','2690','XI GERES - SERRA TALHADA','Serra Talhada','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2700','27','2700','MUNICIPIO IGNORADO - AL','Município ignorado - AL','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2701','27','2701','REGIAO 01','Região 01','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2702','27','2701','REGIAO 02','Região 02','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2703','27','2702','REGIAO 03','Região 03','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2704','27','2702','REGIAO 04','Região 04','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2705','27','2701','REGIAO 05','Região 05','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2800','28','2800','MUNICIPIO IGNORADO - SE','Município ignorado - SE','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2801','28','2890','REGIAO ARACAJU','Aracaju','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2802','28','2890','REGIAO NOSSA SENHORA DO SOCORRO','Nossa Senhora do Socorro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2803','28','2890','REGIAO ESTANCIA','Estância','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2804','28','2890','REGIAO ITABAIANA','Itabaiana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2805','28','2890','REGIAO LAGARTO','Lagarto','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2806','28','2890','REGIAO NOSSA SENHORA DA GLORIA','Nossa Senhora da Glória','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2807','28','2890','REGIAO PROPRIA','Propriá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2808','28','2890','VIII DIRETORIA REGIONAL DE SAUDE','VIII DRS','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2900','29','2900','MUNICIPIO IGNORADO - BA','Município ignorado - BA','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2901','29','2902','SALVADOR','Salvador','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2902','29','2904','FEIRA DE SANTANA','Feira de Santana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2903','29','2902','ALAGOINHAS','Alagoinhas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2904','29','2902','SANTO ANTONIO DE JESUS','Santo Antônio de Jesus','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2905','29','2905','GANDU','Gandu','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2906','29','2905','ILHEUS','Ilhéus','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2907','29','2905','ITABUNA','Itabuna','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2908','29','2906','EUNAPOLIS','Eunápolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2909','29','2906','TEIXEIRA DE FREITAS','Teixeira de Freitas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2910','29','2903','PAULO AFONSO','Paulo Afonso','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2911','29','2902','CICERO DANTAS','Cícero Dantas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2912','29','2904','SERRINHA','Serrinha','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2913','29','2905','JEQUIE','Jequié','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2914','29','2905','ITAPETINGA','Itapetinga','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2915','29','2903','JUAZEIRO','Juazeiro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2916','29','2904','JACOBINA','Jacobina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2917','29','2904','MUNDO NOVO','Mundo Novo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2918','29','2901','ITABERABA','Itaberaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2919','29','2907','BRUMADO','Brumado','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2920','29','2907','VITORIA DA CONQUISTA','Vitória da Conquista','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2921','29','2901','IRECE','Irecê','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2922','29','2908','IBOTIRAMA','Ibotirama','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2923','29','2907','BOQUIRA','Boquira','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2924','29','2907','CAETITE','Caetité','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2925','29','2908','BARREIRAS','Barreiras','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2926','29','2908','SANTA MARIA DA VITORIA','Santa Maria da Vitória','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2927','29','2901','SEABRA','Seabra','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2928','29','2903','SENHOR DO BONFIM','Senhor do Bonfim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2929','29','2902','AMARGOSA','Amargosa','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2930','29','2907','GUANAMBI','Guanambi','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('2931','29','2902','CRUZ DAS ALMAS','Cruz das Almas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3100','31','3100','MUNICIPIO IGNORADO - MG','Município ignorado - MG','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3101','31','3103','BELO HORIZONTE','Belo Horizonte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3103','31','3102','BARBACENA','Barbacena','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3104','31','3104','DIAMANTINA','Diamantina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3105','31','3107','JUIZ DE FORA','Juiz de Fora','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3106','31','3108','MONTES CLAROS','Montes Claros','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3107','31','3109','PATOS DE MINAS','Patos de Minas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3108','31','3110','PONTE NOVA','Ponte Nova','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3109','31','3103','ITABIRA','Itabira','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3110','31','3101','POUSO ALEGRE','Pouso Alegre','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3111','31','3101','VARGINHA','Varginha','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3112','31','3113','UBERLANDIA','Uberlândia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3113','31','3112','UBERABA','Uberaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3114','31','3103','SETE LAGOAS','Sete Lagoas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3115','31','3105','DIVINOPOLIS','Divinópolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3116','31','3106','GOVERNADOR VALADARES','Governador Valadares','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3117','31','3111','TEOFILO OTONI','Teófilo Otoni','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3118','31','3107','UBA','Ubá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3119','31','3111','PEDRA AZUL','Pedra Azul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3120','31','3102','SAO JOAO DEL REI','São João Del Rei','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3121','31','3101','ALFENAS','Alfenas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3122','31','3101','PASSOS','Passos','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3123','31','3106','CORONEL FABRICIANO','Coronel Fabriciano','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3124','31','3110','MANHUMIRIM','Manhumirim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3125','31','3113','ITUIUTABA','Ituiutaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3126','31','3109','UNAI','Unaí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3127','31','3107','LEOPOLDINA','Leopoldina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3128','31','3108','PIRAPORA','Pirapora','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3129','31','3108','JANUARIA','Januária','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3200','32','3200','MUNICIPIO IGNORADO - ES','Município ignorado - ES','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3201','32','3202','SR VITORIA','Vitória','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3202','32','3203','SR CACHOEIRO DO ITAPEMIRIM','Cachoeiro do Itapemirim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3203','32','3201','SR SAO MATEUS','São Mateus','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3204','32','3201','SR COLATINA','Colatina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3205','32','3201','Metropolitana Central Serrana','Metrop Central Serrana','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3206','32','3202','Litoral Norte','Litoral Norte','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3207','32','3202','Extremo Norte','Extremo Norte','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3208','32','3203','Pólo Colatina','Pólo Colatina','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3209','32','3203','Noroeste I','Noroeste I','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3210','32','3203','Noroeste II','Noroeste II','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3211','32','3204','Pólo Caparaó','Pólo Caparaó','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3212','32','3204','Pólo Cachoeiro','Pólo Cachoeiro','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3300','33','3300','MUNICIPIO IGNORADO - RJ','Município ignorado - RJ','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3301','33','3390','BAIA DA ILHA GRANDE','Baía da Ilha Grande','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3302','33','3390','BAIXADA LITORANEA','Baixada Litorânea','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3303','33','3390','CENTRO-SUL FLUMINENSE','Centro-Sul Fluminense','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3304','33','3390','MEDIO PARAIBA','Médio Paraíba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3305','33','3390','METROPOLITANA','Metropolitana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3306','33','3390','NOROESTE FLUMINENSE','Noroeste Fluminense','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3307','33','3390','NORTE FLUMINENSE','Norte Fluminense','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3308','33','3390','SERRANA','Serrana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3500','35','3500','MUNICIPIO IGNORADO - SP','Município ignorado - SP','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3501','35','3590','GRANDE SAO PAULO','Grande São Paulo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3502','35','3590','ARACATUBA','Araçatuba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3503','35','3590','ARARAQUARA','Araraquara','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3504','35','3590','BAIXADA SANTISTA','Baixada Santista','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3505','35','3590','BARRETOS','Barretos','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3506','35','3590','BAURU','Bauru','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3507','35','3590','CAMPINAS','Campinas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3508','35','3590','FRANCA','Franca','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3509','35','3590','MARILIA','Marília','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3510','35','3590','PIRACICABA','Piracicaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3511','35','3590','PRESIDENTE PRUDENTE','Presidente Prudente','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3512','35','3590','REGISTRO','Registro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3513','35','3590','RIBEIRAO PRETO','Ribeirão Preto','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3514','35','3590','SAO JOAO DA BOA VISTA','S.João da Boa Vista','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3515','35','3590','SAO JOSE DO RIO PRETO','S.José do Rio Preto','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3516','35','3590','SOROCABA','Sorocaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3517','35','3590','TAUBATE','Taubaté','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3518','35','3590','Ribeirão Preto','Ribeirão Preto','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3519','35','3590','Santos','Santos','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3520','35','3590','São João da Boa Vista','S.João da Boa Vista','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3521','35','3590','São José dos Campos','S.José dos Campos','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3522','35','3590','São José do Rio Preto','S.José do Rio Preto','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3523','35','3590','Sorocaba','Sorocaba','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('3524','35','3590','Taubaté','Taubaté','N');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4100','41','4100','MUNICIPIO IGNORADO - PR','Município ignorado - PR','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4101','41','4190','PARANAGUA','Paranaguá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4102','41','4190','METROPOLITANA','Metropolitana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4103','41','4190','PONTA GROSSA','Ponta Grossa','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4104','41','4190','IRATI','Irati','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4105','41','4190','GUARAPUAVA','Guarapuava','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4106','41','4190','UNIAO DA VITORIA','União da Vitória','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4107','41','4190','PATO BRANCO','Pato Branco','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4108','41','4190','FRANCISCO BELTRAO','Francisco Beltrão','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4109','41','4190','FOZ DO IGUACU','Foz do Iguaçu','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4110','41','4190','CASCAVEL','Cascavel','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4111','41','4190','CAMPO MOURAO','Campo Mourão','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4112','41','4190','UMUARAMA','Umuarama','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4113','41','4190','CIANORTE','Cianorte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4114','41','4190','PARANAVAI','Paranavaí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4115','41','4190','MARINGA','Maringá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4116','41','4190','APUCARANA','Apucarana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4117','41','4190','LONDRINA','Londrina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4118','41','4190','CORNELIO PROCOPIO','Cornélio Procópio','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4119','41','4190','JACAREZINHO','Jacarezinho','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4120','41','4190','TOLEDO','Toledo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4121','41','4190','TELEMACO BORBA','Telêmaco Borba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4122','41','4190','IVAIPORA','Ivaiporã','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4200','42','4200','MUNICIPIO IGNORADO - SC','Município ignorado - SC','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4201','42','4201','XANXERE','Xanxerê','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4202','42','4208','VIDEIRA','Videira','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4203','42','4208','CONCORDIA','Concórdia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4204','42','4205','RIO DO SUL','Rio do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4205','42','4201','SAO MIGUEL DO OESTE','São Miguel do Oeste','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4206','42','4202','ARARANGUA','Araranguá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4207','42','4205','ITAJAI','Itajaí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4208','42','4208','JOACABA','Joaçaba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4209','42','4205','BLUMENAU','Blumenau','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4210','42','4201','CHAPECO','Chapecó','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4211','42','4207','MAFRA','Mafra','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4212','42','4202','CRICIUMA','Criciúma','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4213','42','4206','JOINVILLE','Joinville','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4214','42','4202','TUBARAO','Tubarão','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4215','42','4203','LAGES','Lages','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4216','42','4207','CANOINHAS','Canoinhas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4217','42','4206','JARAGUA DO SUL','Jaraguá do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4218','42','4204','FLORIANOPOLIS','Florianópolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4300','43','4300','MUNICIPIO IGNORADO - RS','Município ignorado - RS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4301','43','4302','CRS 01 PORTO ALEGRE','Porto Alegre-01','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4302','43','4302','CRS 02 PORTO ALEGRE','Porto Alegre-02','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4303','43','4306','CRS 03 PELOTAS','Pelotas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4304','43','4301','CRS 04 SANTA MARIA','Santa Maria','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4305','43','4305','CRS 05 CAXIAS DO SUL','Caxias do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4306','43','4304','CRS 06 PASSO FUNDO','Passo Fundo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4307','43','4306','CRS 07 BAGE','Bagé','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4308','43','4301','CRS 08 CACHOEIRA DO SUL','Cachoeira do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4309','43','4303','CRS 09 CRUZ ALTA','Cruz Alta','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4310','43','4301','CRS 10 ALEGRETE','Alegrete','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4311','43','4304','CRS 11 ERECHIM','Erechim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4312','43','4303','CRS 12 SANTO ANGELO','Santo Ângelo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4313','43','4307','CRS 13 SANTA CRUZ DO SUL','Santa Cruz do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4314','43','4303','CRS 14 SANTA ROSA','Santa Rosa','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4315','43','4304','CRS 15 PALMEIRA DAS MISSOES','Palmeira das Missões','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4316','43','4307','CRS 16 LAJEADO','Lajeado','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4317','43','4303','CRS 17 IJUI','Ijuí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4318','43','4302','CRS 18 OSORIO','Osório','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('4319','43','4304','CRS 19 FREDERICO WESTPHALEN','Frederico Westphalen','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5000','50','5000','MUNICIPIO IGNORADO - MS','Município ignorado - MS','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5001','50','5090','NCT DE AQUIDAUANA','Aquidauana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5002','50','5090','NCT DE COXIM','Coxim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5003','50','5090','NCT DE DOURADOS','Dourados','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5004','50','5090','NCT DE FATIMA DO SUL','Fátima do Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5005','50','5090','NCT DE JARDIM','Jardim','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5006','50','5090','NCT DE NAVIRAI','Naviraí','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5007','50','5090','NCT DE NOVA ANDRADINA','Nova Andradina','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5008','50','5090','NCT DE PARANAIBA','Paranaíba','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5009','50','5090','NCT DE PONTA PORA','Ponta Porã','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5010','50','5090','NCT DE TRES LAGOAS','Três Lagoas','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5011','50','5090','NCT DE CAMPO GRANDE','Campo Grande','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5012','50','5090','NCT DE CORUMBA','Corumbá','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5100','51','5100','MUNICIPIO IGNORADO - MT','Município ignorado - MT','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5101','51','5190','BAIXADA CUIABANA','Baixada Cuiabana','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5102','51','5190','CACERES','Cáceres','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5103','51','5190','AGUA BOA','Água Boa','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5104','51','5190','ALTA FLORESTA','Alta Floresta','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5105','51','5190','TANGARA DA SERRA','Tangará da Serra','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5106','51','5190','PORTO ALEGRE DO NORTE','Porto Alegre do Norte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5107','51','5190','RONDONOPOLIS','Rondonópolis','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5108','51','5190','BARRA DO GARCAS','Barra do Garças','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5109','51','5190','JUINA','Juína','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5110','51','5190','JUARA','Juara','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5111','51','5190','PEIXOTO DE AZEVEDO','Peixoto de Azevedo','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5112','51','5190','PONTES E LACERDA','Pontes e Lacerda','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5113','51','5190','DIAMANTINO','Diamantino','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5114','51','5190','SINOP','Sinop','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5115','51','5190','COLIDER','Colíder','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5116','51','5190','SAO FELIX DO ARAGUAIA','São Félix do Araguaia','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5200','52','5200','MUNICIPIO IGNORADO - GO','Município ignorado - GO','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5201','52','5201','CENTRAL','Central','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5202','52','5201','CENTRO SUL','Centro Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5203','52','5201','RIO VERMELHO','Rio Vermelho','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5204','52','5201','OESTE I','Oeste I','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5205','52','5201','OESTE II','Oeste II','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5206','52','5202','ENTORNO NORTE','Entorno Norte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5207','52','5202','ENTORNO SUL','Entorno Sul','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5208','52','5202','NORDESTE','Nordeste','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5209','52','5203','NORTE','Norte','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5210','52','5203','SERRA DA MESA','Serra da Mesa','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5211','52','5203','PIRINEUS','Pirineus','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5212','52','5203','SAO PATRICIO','São Patrício','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5213','52','5204','SUDOESTE I','Sudoeste I','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5214','52','5204','SUDOESTE II','Sudoeste II','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5215','52','5205','ESTRADA DE FERRO','Estrada de Ferro','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5216','52','5205','SUL','Sul','S');

INSERT INTO dbgeral.tb_regional_saude
VALUES
('5217','52','5202','NORDESTE II','Nordeste II','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5298','52','5298','MUNICIPIOS TRANSFERIDOS PARA TOCANTINS','Transf p Tocantins','S');
 
INSERT INTO dbgeral.tb_regional_saude
VALUES
('5301','53','5301','DISTRITO FEDERAL','Distrito Federal','S');

INSERT INTO dbgeral.tb_regional_saude 
VALUES
('1514','15','1506','BAIXO AMAZONAS','Baixo Amazonas','S');
