INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('2','01.11-2','CULTIVO DE CEREAIS PARA GRAOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('3','01.12-0','CULTIVO DE ALGODAO HERBACEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('4','01.14-7','CULTIVO DE FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('5','01.15-5','CULTIVO DE SOJA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('6','01.19-8','CULTIVO DE OUTROS PRODUTOS DE LAVOURA TEMPORARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('7','01.21-0','CULTIVO DE HORTALICAS, LEGUMES E OUTROS PRODUTOS DA HORTICULTURA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('8','01.22-8','CULTIVO DE FLORES, PLANTAS ORNAMENTAIS E PRODUTOS DE VIVEIRO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('9','01.31-7','CULTIVO DE FRUTAS CITRICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('10','01.32-5','CULTIVO DE CAFE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('11','01.33-3','CULTIVO DE CACAU');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('12','01.34-1','CULTIVO DE UVA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('13','01.39-2','CULTIVO DE OUTROS PRODUTOS DE LAVOURA PERMANENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('14','01.41-4','CRIACAO DE BOVINOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('15','01.42-2','CRIACAO DE OUTROS ANIMAIS DE GRANDE PORTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('16','01.43-0','CRIACAO DE OVINOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('17','01.44-9','CRIACAO DE SUINOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('18','01.45-7','CRIACAO DE AVES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('19','01.46-5','CRIACAO DE OUTROS ANIMAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('20','01.50-3','PRODUCAO MISTA  LAVOURA E PECUARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('21','01.61-9','ATIVIDADES DE SERVICOS RELACIONADOS COM A AGRICULTURA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('22','01.62-7','ATIVIDADES DE SERVICOS RELACIONADOS COM A PECUARIA, EXCETO ATIVIDADES VETERINARIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('23','01.70-8','CACA, REPOVOAMENTO CINEGETICO E SERVICOS RELACIONADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('24','02.11-9','SILVICULTURA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('25','02.12-7','EXPLORACAO FLORESTAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('26','02.13-5','ATIVIDADES DE SERVICOS RELACIONADOS COM A SILVICULTURA E A EXPLORACAO FLORESTAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('27','05.11-8','PESCA E SERVICOS RELACIONADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('28','10.00-6','EXTRACAO DE CARVAO MINERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('29','11.10-0','EXTRACAO DE PETROLEO E GAS NATURAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('30','11.20-7','ATIVIDADES DE SERVICOS RELACIONADOS COM A EXTRACAO DE PETROLEO E GAS - EXCETO A PROSPECCAO REALIZADA POR TERCEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('31','13.10-2','EXTRACAO DE MINERIO DE FERRO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('32','13.21-8','EXTRACAO DE MINERIO DE ALUMINIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('33','13.22-6','EXTRACAO DE MINERIO DE ESTANHO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('34','13.23-4','EXTRACAO DE MINERIO DE MANGANES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('35','13.24-2','EXTRACAO DE MINERIO DE METAIS PRECIOSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('36','13.25-0','EXTRACAO DE MINERAIS RADIOATIVOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('37','13.29-3','EXTRACAO DE OUTROS MINERAIS METALICOS NAO-FERROSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('38','14.10-9','EXTRACAO DE PEDRA, AREIA E ARGILA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('39','14.21-4','EXTRACAO DE MINERAIS PARA FABRICACAO DE ADUBOS, FERTILIZANTES E PRODUTOS QUIMICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('40','14.22-2','EXTRACAO E REFINO DE SAL MARINHO E SAL-GEMA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('41','14.29-0','EXTRACAO DE OUTROS MINERAIS NAO-METALICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('42','15.11-3','ABATE DE RESES, PREPARACAO DE PRODUTOS DE CARNE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('43','15.12-1','ABATE DE AVES E OUTROS PEQUENOS ANIMAIS E PREPARACAO DE PRODUTOS DE CARNE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('44','15.13-0','PREPARACAO DE CARNE, BANHA E PRODUTOS DE SALSICHARIA NAO ASSOCIADA AO ABATE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('45','15.14-8','PREPARACAO E PRESERVACAO DO PESCADO E FABRICACAO DE CONSERVAS DE PEIXES, CRUSTACEOS E MOLUSCOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('46','15.21-0','PROCESSAMENTO, PRESERVACAO E PRODUCAO DE CONSERVAS DE FRUTAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('47','15.22-9','PROCESSAMENTO, PRESERVACAO E PRODUCAO DE CONSERVAS DE LEGUMES E OUTROS VEGETAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('48','15.23-7','PRODUCAO DE SUCOS DE FRUTAS E DE LEGUMES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('49','15.31-8','PRODUCAO DE OLEOS VEGETAIS EM BRUTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('50','15.32-6','REFINO DE OLEOS VEGETAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('51','15.33-4','PREPARACAO DE MARGARINA E DE OUTRAS GORDURAS VEGETAIS E DE OLEOS DE ORIGEM ANIMAL NAO COMESTIVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('52','15.41-5','PREPARACAO DO LEITE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('53','15.42-3','FABRICACAO DE PRODUTOS DO LATICINIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('54','15.43-1','FABRICACAO DE SORVETES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('55','15.51-2','BENEFICIAMENTO DE ARROZ E FABRICACAO DE PRODUTOS DO ARROZ');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('56','15.52-0','MOAGEM DE TRIGO E FABRICACAO DE DERIVADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('57','15.53-9','FABRICACAO DE FARINHA DE MANDIOCA E DERIVADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('58','15.54-7','FABRICACAO DE FARINHA DE MILHO E DERIVADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('59','15.55-5','FABRICACAO DE AMIDOS E FECULAS DE VEGETAIS E FABRICACAO DE OLEOS DE MILHO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('60','15.56-3','FABRICACAO DE RACOES BALANCEADAS PARA ANIMAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('61','15.59-8','BENEFICIAMENTO, MOAGEM  E PREPARACAO DE OUTROS PRODUTOS DE ORIGEM VEGETAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('62','15.62-8','REFINO E MOAGEM DE ACUCAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('63','15.71-7','TORREFACAO E MOAGEM DE CAFE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('64','15.81-4','FABRICACAO DE PRODUTOS DE PADARIA, CONFEITARIA E PASTELARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('65','15.82-2','FABRICACAO DE BISCOITOS E BOLACHAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('66','15.83-0','PRODUCAO DE DERIVADOS DO CACAU E ELABORACAO DE CHOCOLATES, BALAS, GOMAS DE MASCAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('67','15.84-9','FABRICACAO DE MASSAS ALIMENTICIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('68','15.85-7','PREPARACAO DE ESPECIARIAS, MOLHOS, TEMPEROS E CONDIMENTOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('69','15.86-5','PREPARACAO DE PRODUTOS  DIETETICOS, ALIMENTOS PARA CRIANCAS E OUTROS ALIMENTOS CONSERVADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('70','15.89-0','FABRICACAO DE OUTROS PRODUTOS ALIMENTICIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('71','15.91-1','FABRICACAO, RETIFICACAO, HOMOGENEIZACAO E MISTURA DE AGUARDENTES E OUTRAS BEBIDAS DESTILADAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('72','15.92-0','FABRICACAO DE VINHO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('73','15.93-8','FABRICACAO DE MALTE, CERVEJAS E CHOPES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('74','15.94-6','ENGARRAFAMENTO E GASEIFICACAO DE AGUAS MINERAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('75','15.95-4','FABRICACAO DE REFRIGERANTES E REFRESCOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('76','16.00-4','FABRICACAO DE PRODUTOS DO FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('77','17.11-6','BENEFICIAMENTO DE ALGODAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('78','17.19-1','BENEFICIAMENTO DE OUTRAS FIBRAS TEXTEIS NATURAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('79','17.21-3','FIACAO DE ALGODAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('80','17.22-1','FIACAO DE FIBRAS TEXTEIS NATURAIS, EXCETO ALGODAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('81','17.23-0','FIACAO DE FIBRAS ARTIFICIAIS OU SINTETICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('82','17.24-8','FABRICACAO DE LINHAS E FIOS PARA COSTURAR E BORDAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('83','17.31-0','TECELAGEM DE ALGODAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('84','17.32-9','TECELAGEM DE FIOS DE FIBRAS TEXTEIS NATURAIS, EXCETO ALGODAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('85','17.33-7','TECELAGEM DE FIOS E FILAMENTOS CONTINUOS ARTIFICIAIS OU SINTETICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('86','17.41-8','FABRICACAO DE ARTIGOS DE TECIDO DE USO DOMESTICO, INCLUINDO TECELAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('87','17.49-3','FABRICACAO DE OUTROS ARTEFATOS TEXTEIS, INCLUINDO TECELAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('88','17.50-7','ACABAMENTOS EM FIOS, TECIDOS E ARTIGOS TEXTEIS, POR TERCEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('89','17.61-2','FABRICACAO DE ARTEFATOS TEXTEIS A PARTIR DE TECIDOS EXCETO VESTUARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('90','17.62-0','FABRICACAO DE ARTEFATOS DE TAPECARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('91','17.63-9','FABRICACAO DE ARTEFATOS DE CORDOARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('92','17.64-7','FABRICACAO DE TECIDOS ESPECIAIS - INCLUSIVE ARTEFATOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('93','17.69-8','FABRICACAO DE OUTROS ARTIGOS TEXTEIS - EXCETO VESTUARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('94','17.71-0','FABRICACAO DE TECIDOS DE MALHA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('95','17.72-8','FABRICACAO DE MEIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('96','17.79-5','FABRICACAO DE OUTROS ARTIGOS DO VESTUARIO PRODUZIDOS EM MALHARIAS (TRICOTAGENS)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('97','18.11-2','CONFECCAO DE ROUPAS INTIMAS, BLUSAS, CAMISAS E SEMELHANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('98','18.12-0','CONFECCAO DE PECAS DO VESTUARIO - EXCETO ROUPAS INTIMAS, BLUSAS, CAMISAS  E SEMELHANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('99','18.13-9','CONFECCAO DE ROUPAS PROFISSIONAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('100','18.21-0','FABRICACAO DE ACESSORIOS DO VESTUARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('101','18.22-8','FABRICACAO DE ACESSORIOS PARA SEGURANCA INDUSTRIAL E PESSOAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('102','19.10-0','CURTIMENTO E OUTRAS PREPARACOES DE COURO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('103','19.21-6','FABRICACAO DE MALAS, BOLSAS, VALISES E OUTROS ARTEFATOS PARA VIAGEM, DE QUALQUER MATERIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('104','19.29-1','FABRICACAO DE OUTROS ARTEFATOS DE COURO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('105','19.31-3','FABRICACAO DE CALCADOS DE COURO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('106','19.32-1','FABRICACAO DE TENIS DE QUALQUER MATERIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('107','19.33-0','FABRICACAO DE CALCADOS DE PLASTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('108','19.39-9','FABRICACAO DE CALCADOS DE OUTROS MATERIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('109','20.10-9','DESDOBRAMENTO DE MADEIRA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('110','16.21-8','FABRICACAO DE MADEIRA LAMINADA E DE CHAPAS DE MADEIRA COMPENSADA, PRENSADA OU AGLOMERADA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('111','20.22-2','FABRICACAO DE ESQUADRIAS DE MADEIRA, DE CASAS DE MADEIRA PRE-FABRICADAS, DE ESTRUTURAS DE MADEIRA E ARTIGOS DE CARPINTARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('112','20.23-0','FABRICACAO DE ARTEFATOS DE TANOARIA E EMBALAGENS DE MADEIRA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('113','20.29-0','FABRICACAO DE ARTEFATOS DIVERSOS DE MADEIRA, PALHA, CORTICA E MATERIAL TRANCADO - EXCETO MOVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('114','21.10-5','FABRICACAO DE CELULOSE E OUTRAS PASTAS PARA A FABRICACAO DE PAPEL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('115','21.21-0','FABRICACAO DE PAPEL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('116','21.22-9','FABRICACAO DE PAPELAO LISO, CARTOLINA E CARTAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('117','21.31-8','FABRICACAO DE EMBALAGENS DE PAPEL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('118','21.32-6','FABRICACAO DE EMBALAGENS  DE PAPELAO - INCLUSIVE A FABRICACAO DE PAPELAO CORRUGADO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('119','21.41-5','FABRICACAO DE ARTEFATOS DE PAPEL, PAPELAO, CARTOLINA E CARTAO PARA ESCRITORIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('120','21.42-3','FABRICACAO DE FITAS E FORMULARIOS CONTINUOS - IMPRESSOS OU NAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('121','21.49-0','FABRICACAO DE OUTROS ARTEFATOS DE PASTAS, PAPEL, PAPELAO, CARTOLINA E CARTAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('122','22.14-4','EDICAO DE DISCOS, FITAS E OUTROS MATERIAIS GRAVADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('123','22.15-2','EDICAO DE LIVROS, REVISTAS E JORNAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('124','22.16-0','EDICAO E IMPRESSAO DE LIVROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('125','22.17-9','EDICAO E IMPRESSAO DE JORNAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('126','22.18-7','EDICAO E IMPRESSAO DE REVISTAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('127','22.19-5','EDICAO; EDICAO E IMPRESSAO DE OUTROS PRODUTOS GRAFICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('128','22.21-7','IMPRESSAO DE JORNAIS, REVISTAS E LIVROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('129','22.22-5','IMPRESSAO DE MATERIAL ESCOLAR  E DE MATERIAL PARA USOS INDUSTRIAL E COMERCIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('130','22.29-2','EXECUCAO DE OUTROS SERVICOS GRAFICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('131','22.31-4','REPRODUCAO DE DISCOS E FITAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('132','22.32-2','REPRODUCAO DE FITAS DE VIDEOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('133','22.34-9','REPRODUCAO DE SOFTWARES EM DISQUETES E FITAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('134','23.10-8','COQUERIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('135','23.21-3','REFINO DE PETROLEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('136','23.29-9','OUTRAS FORMAS DE PRODUCAO DE DERIVADOS DO PETROLEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('137','23.30-2','ELABORACAO DE COMBUSTIVEIS NUCLEARES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('138','23.40-0','PRODUCAO DE ALCOOL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('139','24.11-2','FABRICACAO DE CLORO E ALCALIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('140','24.12-0','FABRICACAO DE INTERMEDIARIOS PARA FERTILIZANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('141','24.13-9','FABRICACAO DE FERTILIZANTES FOSFATADOS, NITROGENADOS E POTASSICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('142','24.14-7','FABRICACAO DE GASES INDUSTRIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('143','24.19-8','FABRICACAO DE OUTROS PRODUTOS INORGANICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('144','24.21-0','FABRICACAO DE PRODUTOS PETROQUIMICOS BASICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('145','24.22-8','FABRICACAO DE INTERMEDIARIOS PARA RESINAS E FIBRAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('146','24.29-5','FABRICACAO DE OUTROS PRODUTOS QUIMICOS ORGANICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('147','24.31-7','FABRICACAO DE RESINAS TERMOPLASTICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('148','24.32-5','FABRICACAO DE RESINAS TERMOFIXAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('149','24.33-3','FABRICACAO DE ELASTOMEROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('150','24.41-4','FABRICACAO DE FIBRAS, FIOS, CABOS E FILAMENTOS CONTINUOS ARTIFICIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('151','24.42-2','FABRICACAO DE FIBRAS, FIOS, CABOS E FILAMENTOS CONTINUOS SINTETICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('152','24.51-1','FABRICACAO DE PRODUTOS FARMOQUIMICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('153','24.52-0','FABRICACAO DE MEDICAMENTOS PARA USO HUMANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('154','24.53-8','FABRICACAO DE MEDICAMENTOS PARA USO VETERINARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('155','24.54-6','FABRICACAO DE MATERIAIS PARA USOS MEDICOS, HOSPITALARES E ODONTOLOGICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('156','24.61-9','FABRICACAO DE INSETICIDAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('157','24.62-7','FABRICACAO DE FUNGICIDAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('158','24.63-5','FABRICACAO DE HERBICIDAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('159','24.69-4','FABRICACAO DE OUTROS DEFENSIVOS AGRICOLAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('160','24.71-6','FABRICACAO DE SABOES, SABONETES E DETERGENTES SINTETICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('161','24.72-4','FABRICACAO DE PRODUTOS DE LIMPEZA E POLIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('162','24.73-2','FABRICACAO DE ARTIGOS DE PERFUMARIA E COSMETICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('163','24.81-3','FABRICACAO DE TINTAS, VERNIZES, ESMALTES E LACAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('164','24.82-1','FABRICACAO DE TINTAS DE IMPRESSAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('165','24.83-0','FABRICACAO DE IMPERMEABILIZANTES, SOLVENTES E PRODUTOS AFINS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('166','24.91-0','FABRICACAO DE ADESIVOS E SELANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('167','24.92-9','FABRICACAO DE EXPLOSIVOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('168','24.93-7','FABRICACAO DE CATALISADORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('169','24.94-5','FABRICACAO DE ADITIVOS DE USO INDUSTRIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('170','24.95-3','FABRICACAO DE CHAPAS, FILMES, PAPEIS E OUTROS MATERIAIS E PRODUTOS QUIMICOS PARA FOTOGRAFIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('171','24.96-1','FABRICACAO DE DISCOS E FITAS VIRGENS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('172','24.99-6','FABRICACAO DE OUTROS PRODUTOS QUIMICOS NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('173','25.11-9','FABRICACAO DE PNEUMATICOS E DE CAMARAS-DE-AR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('174','25.12-7','RECONDICIONAMENTO DE PNEUMATICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('175','25.19-4','FABRICACAO DE ARTEFATOS DIVERSOS DE BORRACHA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('176','25.21-6','FABRICACAO DE LAMINADOS PLANOS E TUBULARES DE PLASTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('177','25.22-4','FABRICACAO DE EMBALAGEM DE PLASTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('178','25.29-1','FABRICACAO DE ARTEFATOS DIVERSOS DE PLASTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('179','26.11-5','FABRICACAO DE VIDRO PLANO E DE SEGURANCA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('180','26.12-3','FABRICACAO DE EMBALAGENS DE VIDRO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('181','26.19-0','FABRICACAO DE ARTIGOS DE VIDRO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('182','26.20-4','FABRICACAO DE CIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('183','26.30-1','FABRICACAO DE ARTEFATOS DE CONCRETO, CIMENTO, FIBROCIMENTO, GESSO E ESTUQUE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('184','26.41-7','FABRICACAO DE PRODUTOS CERAMICOS NAO-REFRATARIOS PARA USO ESTRUTURAL NA CONSTRUCAO CIVIL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('185','26.42-5','FABRICACAO DE PRODUTOS CERAMICOS REFRATARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('186','26.49-2','FABRICACAO DE PRODUTOS CERAMICOS NAO-REFRATARIOS PARA USOS DIVERSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('187','26.91-3','BRITAMENTO, APARELHAMENTO E OUTROS TRABALHOS EM PEDRAS (NAO ASSOCIADOS A EXTRACAO)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('188','26.92-1','FABRICACAO DE CAL VIRGEM, CAL HIDRATADA E GESSO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('189','26.99-9','FABRICACAO DE OUTROS PRODUTOS DE MINERAIS NAO-METALICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('190','27.13-8','PRODUCAO DE FERRO-GUSA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('191','27.14-6','PRODUCAO DE FERROLIGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('192','27.23-5','PRODUCAO DE SEMI-ACABADOS DE ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('193','27.24-3','PRODUCAO DE LAMINADOS PLANOS DE ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('194','27.25-1','PRODUCAO DE LAMINADOS LONGOS DE ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('195','27.26-0','PRODUCAO DE RELAMINADOS, TREFILADOS E PERFILADOS DE ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('196','27.31-6','FABRICACAO DE TUBOS DE ACO COM COSTURA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('197','27.39-1','FABRICACAO DE OUTROS TUBOS DE FERRO E ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('198','27.41-3','METALURGIA DO ALUMINIO E SUAS LIGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('199','27.42-1','METALURGIA DOS METAIS PRECIOSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('200','27.49-9','METALURGIA DE OUTROS METAIS NAO-FERROSOS E SUAS LIGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('201','27.51-0','FABRICACAO DE PECAS FUNDIDAS DE FERRO E ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('202','27.52-9','FABRICACAO DE PECAS FUNDIDAS DE METAIS NAO-FERROSOS E SUAS LIGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('203','28.11-8','FABRICACAO DE ESTRUTURAS METALICAS PARA EDIFICIOS, PONTES, TORRES DE TRANSMISSAO, ANDAIMES E OUTROS FINS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('204','28.12-6','FABRICACAO DE ESQUADRIAS DE METAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('205','28.13-4','FABRICACAO DE OBRAS DE CALDEIRARIA PESADA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('206','28.21-5','FABRICACAO DE TANQUES, RESERVATORIOS METALICOS E CALDEIRAS PARA AQUECIMENTO CENTRAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('207','28.22-3','FABRICACAO DE CALDEIRAS GERADORAS DE VAPOR - EXCETO PARA AQUECIMENTO CENTRAL E PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('208','28.31-2','PRODUCAO DE FORJADOS DE ACO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('209','28.32-0','PRODUCAO DE FORJADOS DE METAIS NAO-FERROSOS E SUAS LIGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('210','28.33-9','FABRICACAO DE ARTEFATOS ESTAMPADOS DE METAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('211','28.34-7','METALURGIA DO PO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('212','28.39-8','TEMPERA, CEMENTACAO E TRATAMENTO TERMICO DO ACO, SERVICOS DE USINAGEM, GALVANOTECNICA E SOLDA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('213','28.41-0','FABRICACAO DE ARTIGOS DE CUTELARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('214','28.42-8','FABRICACAO DE ARTIGOS DE SERRALHERIA - EXCETO ESQUADRIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('215','28.43-6','FABRICACAO DE FERRAMENTAS MANUAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('216','28.81-9','MANUTENCAO E REPARACAO DE TANQUES, RESERVATORIOS METALICOS E CALDEIRAS PARA AQUECIMENTO CENTRAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('217','28.82-7','MANUTENCAO E REPARACAO DE CALDEIRAS GERADORAS DE VAPOR - EXCETO PARA AQUECIMENTO CENTRAL E PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('218','28.91-6','FABRICACAO DE EMBALAGENS METALICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('219','28.92-4','FABRICACAO DE ARTEFATOS DE TREFILADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('220','28.93-2','FABRICACAO DE ARTIGOS DE FUNILARIA E DE ARTIGOS DE METAL PARA USOS DOMESTICO E PESSOAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('221','28.99-1','FABRICACAO DE OUTROS PRODUTOS ELABORADOS DE METAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('222','29.11-4','FABRICACAO DE MOTORES ESTACIONARIOS DE COMBUSTAO INTERNA, TURBINAS E OUTRAS MAQUINAS MOTRIZES NAO-ELETRICAS - EXCETO PARA AVIOES E VEICULOS RODOVIARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('223','29.12-2','FABRICACAO DE BOMBAS E CARNEIROS HIDRAULICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('224','29.13-0','FABRICACAO DE VALVULAS, TORNEIRAS E REGISTROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('225','29.14-9','FABRICACAO DE COMPRESSORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('226','29.15-7','FABRICACAO DE EQUIPAMENTOS DE TRANSMISSAO PARA FINS INDUSTRIAIS - INCLUSIVE ROLAMENTOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('227','29.21-1','FABRICACAO DE FORNOS INDUSTRIAIS, APARELHOS E EQUIPAMENTOS NAO-ELETRICOS PARA INSTALACOES TERMICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('228','29.22-0','FABRICACAO DE ESTUFAS E FORNOS ELETRICOS PARA FINS INDUSTRIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('229','29.23-8','FABRICACAO DE MAQUINAS, EQUIPAMENTOS E APARELHOS PARA TRANSPORTE E ELEVACAO DE CARGAS E PESSOAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('230','29.24-6','FABRICACAO DE MAQUINAS E APARELHOS DE REFRIGERACAO E VENTILACAO DE USOS INDUSTRIAL E COMERCIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('231','29.25-4','FABRICACAO DE APARELHOS DE AR-CONDICIONADO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('232','29.29-7','FABRICACAO DE OUTRAS MAQUINAS E EQUIPAMENTOS DE USO GERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('233','29.31-9','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA AGRICULTURA, AVICULTURA E OBTENCAO DE PRODUTOS ANIMAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('234','29.32-7','FABRICACAO DE TRATORES AGRICOLAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('235','29.40-8','FABRICACAO DE MAQUINAS-FERRAMENTA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('236','29.51-3','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA A PROSPECCAO E EXTRACAO DE PETROLEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('237','29.52-1','FABRICACAO DE OUTRAS MAQUINAS E EQUIPAMENTOS DE USO NA EXTRACAO MINERAL E CONSTRUCAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('238','29.53-0','FABRICACAO DE TRATORES DE ESTEIRA E TRATORES DE USO NA EXTRACAO MINERAL E CONSTRUCAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('239','29.54-8','FABRICACAO DE MAQUINAS E EQUIPAMENTOS DE TERRAPLENAGEM E PAVIMENTACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('240','29.61-0','FABRICACAO DE MAQUINAS PARA A INDUSTRIA METALURGICA - EXCETO MAQUINAS-FERRAMENTA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('241','29.62-9','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA AS INDUSTRIAS ALIMENTAR, DE BEBIDA E FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('242','29.63-7','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA A INDUSTRIA TEXTIL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('243','29.64-5','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA AS INDUSTRIAS DO  VESTUARIO E DE COURO E CALCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('244','29.65-3','FABRICACAO DE MAQUINAS E EQUIPAMENTOS PARA AS INDUSTRIAS DE CELULOSE, PAPEL E PAPELAO E ARTEFATOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('245','29.69-6','FABRICACAO DE OUTRAS MAQUINAS E EQUIPAMENTOS DE USO ESPECIFICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('246','29.71-8','FABRICACAO DE ARMAS DE FOGO E MUNICOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('247','29.72-6','FABRICACAO DE EQUIPAMENTO BELICO PESADO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('248','29.81-5','FABRICACAO DE FOGOES, REFRIGERADORES E MAQUINAS DE LAVAR E SECAR PARA USO DOMESTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('249','29.89-0','FABRICACAO DE OUTROS APARELHOS ELETRODOMESTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('250','29.91-2','MANUTENCAO E REPARACAO DE MOTORES, BOMBAS, COMPRESSORES E EQUIPAMENTOS DE TRANSMISSAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('251','29.92-0','MANUTENCAO E REPARACAO DE MAQUINAS E EQUIPAMENTOS DE USO GERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('252','29.93-9','MANUTENCAO E REPARACAO DE TRATORES E DE MAQUINAS E EQUIPAMENTOS PARA AGRICULUTRA, AVICULTURA E OBTENCAO DE PRODUTOS ANIMAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('253','29.94-7','MANUTENCAO E REPARACAO DE MAQUINAS-FERRAMENTA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('254','29.95-5','MANUTENCAO E REPARACAO DE MAQUINAS E EQUIPAMENTOS DE USO NA EXTRACAO MINERAL E CONSTRUCAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('255','29.96-3','MANUTENCAO E REPARACAO DE MAQUINAS E EQUIPAMENTOS DE USO ESPECIFICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('256','30.11-2','FABRICACAO DE MAQUINAS DE ESCREVER E CALCULAR, COPIADORAS E OUTROS EQUIPAMENTOS NAO-ELETRONICOS PARA ESCRITORIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('257','30.12-0','FABRICACAO DE MAQUINAS DE ESCREVER E CALCULAR, COPIADORAS E OUTROS EQUIPAMENTOS ELETRONICOS DESTINADOS A AUTOMACAO GERENCIAL E COMERCIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('258','30.21-0','FABRICACAO DE COMPUTADORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('259','30.22-8','FABRICACAO DE EQUIPAMENTOS PERIFERICOS PARA MAQUINAS ELETRONICAS PARA TRATAMENTO DE INFORMACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('260','31.11-9','FABRICACAO DE GERADORES DE CORRENTE CONTINUA OU ALTERNADA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('261','31.12-7','FABRICACAO DE TRANSFORMADORES, INDUTORES, CONVERSORES, SINCRONIZADORES E SEMELHANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('262','31.13-5','FABRICACAO DE MOTORES ELETRICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('263','31.21-6','FABRICACAO DE SUBESTACOES, QUADROS DE COMANDO, REGULADORES DE VOLTAGEM E OUTROS APARELHOS E EQUIPAMENTOS PARA DISTRIBUICAO E CONTROLE DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('264','31.22-4','FABRICACAO DE MATERIAL ELETRICO PARA INSTALACOES EM CIRCUITO DE CONSUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('265','31.30-5','FABRICACAO DE FIOS, CABOS E CONDUTORES ELETRICOS ISOLADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('266','31.41-0','FABRICACAO DE PILHAS, BATERIAS E ACUMULADORES ELETRICOS - EXCETO PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('267','31.42-9','FABRICACAO DE BATERIAS E ACUMULADORES PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('268','31.51-8','FABRICACAO DE LAMPADAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('269','31.52-6','FABRICACAO DE LUMINARIAS E EQUIPAMENTOS DE ILUMINACAO - EXCETO PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('270','31.60-7','FABRICACAO DE MATERIAL ELETRICO PARA VEICULOS - EXCETO BATERIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('271','31.81-0','MANUTENCAO E REPARACAO DE GERADORES, TRANSFORMADORES E MOTORES ELETRICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('272','31.82-8','MANUTENCAO E REPARACAO DE BATERIAS E ACUMULADORES ELETRICOS - EXCETO PARA VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('273','31.89-5','MANUTENCAO E REPARACAO DE MAQUINAS, APARELHOS E MATERIAIS ELETRICOS NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('274','31.91-7','FABRICACAO DE ELETRODOS, CONTATOS E OUTROS ARTIGOS DE CARVAO E GRAFITA PARA USO ELETRICO, ELETROIMAS E ISOLADORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('275','31.92-5','FABRICACAO DE APARELHOS E UTENSILIOS PARA SINALIZACAO E ALARME');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('276','31.99-2','FABRICACAO DE OUTROS APARELHOS OU EQUIPAMENTOS ELETRICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('277','32.10-7','FABRICACAO DE MATERIAL ELETRONICO BASICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('278','32.21-2','FABRICACAO DE EQUIPAMENTOS TRANSMISSORES DE RADIO E TELEVISAO E DE EQUIPAMENTOS PARA ESTACOES TELEFONICAS, PARA RADIOTELEFONIA E RADIOTELEGRAFIA - INCLUSIVE DE MICROONDAS E REPETIDORAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('279','32.22-0','FABRICACAO DE APARELHOS TELEFONICOS, SISTEMAS DE INTERCOMUNICACAO E SEMELHANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('280','32.30-1','FABRICACAO DE APARELHOS RECEPTORES DE RADIO E TELEVISAO E DE REPRODUCAO, GRAVACAO OU AMPLIFICACAO DE SOM E VIDEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('281','32.90-5','MANUTENCAO E REPARACAO DE APARELHOS E EQUIPAMENTOS DE TELEFONIA E RADIOTELEFONIA E DE TRANSMISSORES DE TELEVISAO E RADIO - EXCETO TELEFONES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('282','33.10-3','FABRICACAO DE APARELHOS E INSTRUMENTOS PARA USOS MEDICO-HOSPITALARES, ODONTOLOGICOS E DE LABORATORIOS E APARELHOS ORTOPEDICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('283','33.20-0','FABRICACAO DE APARELHOS E INSTRUMENTOS DE MEDIDA, TESTE E CONTROLE - EXCETO EQUIPAMENTOS PARA CONTROLE DE PROCESSOS INDUSTRIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('284','33.30-8','FABRICACAO DE MAQUINAS, APARELHOS E EQUIPAMENTOS DE SISTEMAS ELETRONICOS DEDICADOS A AUTOMACAO INDUSTRIAL E CONTROLE DO PROCESSO PRODUTIVO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('285','33.40-5','FABRICACAO DE APARELHOS, INSTRUMENTOS E MATERIAIS OPTICOS, FOTOGRAFICOS E CINEMATOGRAFICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('286','33.50-2','FABRICACAO DE CRONOMETROS E RELOGIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('287','33.91-0','MANUTENCAO E REPARACAO DE EQUIPAMENTOS MEDICO-HOSPITALARES, ODONTOLOGICOS E DE LABORATORIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('288','33.92-8','MANUTENCAO E REPARACAO DE APARELHOS E INSTRUMENTOS DE MEDIDA, TESTE E CONTROLE - EXCETO EQUIPAMENTOS DE CONTROLE DE PROCESSOS INDUSTRIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('289','33.93-6','MANUTENCAO E REPARACAO DE MAQUINAS, APARELHOS E EQUIPAMENTOS DE SISTEMAS ELETRONICOS DEDICADOS A AUTOMACAO INDUSTRIAL E CONTROLE DO PROCESSO PRODUTIVO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('290','33.94-4','MANUTENCAO E REPARACAO DE INSTRUMENTOS OPTICOS E CINEMATOGRAFICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('291','34.10-0','FABRICACAO DE AUTOMOVEIS, CAMIONETAS E UTILITARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('292','34.20-7','FABRICACAO DE CAMINHOES E ONIBUS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('293','34.31-2','FABRICACAO DE CABINES, CARROCERIAS E REBOQUES PARA CAMINHAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('294','34.32-0','FABRICACAO DE CARROCERIAS PARA ONIBUS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('295','34.39-8','FABRICACAO DE CABINES, CARROCERIAS E REBOQUES PARA OUTROS VEICULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('296','34.41-0','FABRICACAO DE PECAS E ACESSORIOS PARA O SISTEMA MOTOR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('297','34.42-8','FABRICACAO DE PECAS E ACESSORIOS PARA OS SISTEMAS DE MARCHA E TRANSMISSAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('298','34.43-6','FABRICACAO DE PECAS E ACESSORIOS PARA O SISTEMA DE FREIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('299','34.44-4','FABRICACAO DE PECAS E ACESSORIOS PARA O SISTEMA DE DIRECAO E SUSPENSAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('300','34.49-5','FABRICACAO DE OUTRAS PECAS E ACESSORIOS PARA VEICULOS AUTOMOTORES NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('301','34.50-9','RECONDICIONAMENTO OU RECUPERACAO DE MOTORES PARA VEICULOS AUTOMOTORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('302','35.11-4','CONSTRUCAO E REPARACAO DE EMBARCACOES E ESTRUTURAS FLUTUANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('303','35.12-2','CONSTRUCAO E REPARACAO DE EMBARCACOES PARA ESPORTE E LAZER');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('304','35.21-1','CONSTRUCAO E MONTAGEM DE LOCOMOTIVAS, VAGOES E OUTROS MATERIAIS RODANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('305','35.22-0','FABRICACAO DE PECAS E ACESSORIOS PARA VEICULOS FERROVIARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('306','35.23-8','REPARACAO DE VEICULOS FERROVIARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('307','35.31-9','CONSTRUCAO E MONTAGEM DE AERONAVES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('308','35.32-7','REPARACAO DE AERONAVES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('309','35.91-2','FABRICACAO DE MOTOCICLETAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('310','35.92-0','FABRICACAO DE BICICLETAS E TRICICLOS NAO-MOTORIZADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('311','35.99-8','FABRICACAO DE OUTROS EQUIPAMENTOS DE TRANSPORTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('312','36.11-0','FABRICACAO DE MOVEIS COM PREDOMINANCIA DE MADEIRA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('313','36.12-9','FABRICACAO DE MOVEIS COM PREDOMINANCIA DE METAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('314','36.13-7','FABRICACAO DE MOVEIS DE OUTROS MATERIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('315','36.14-5','FABRICACAO DE COLCHOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('316','36.91-9','LAPIDACAO DE PEDRAS PRECIOSAS E SEMI-PRECIOSAS, FABRICACAO DE ARTEFATOS DE OURIVESARIA E JOALHERIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('317','36.92-7','FABRICACAO DE INSTRUMENTOS MUSICAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('318','36.93-5','FABRICACAO DE ARTEFATOS PARA CACA, PESCA E ESPORTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('319','36.94-3','FABRICACAO DE BRINQUEDOS E DE JOGOS RECREATIVOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('320','36.95-1','FABRICACAO DE CANETAS, LAPIS, FITAS IMPRESSORAS PARA MAQUINAS E OUTROS ARTIGOS PARA ESCRITORIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('321','36.96-0','FABRICACAO DE AVIAMENTOS PARA COSTURA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('322','36.97-8','FABRICACAO DE ESCOVAS, PINCEIS E VASSOURAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('323','36.99-4','FABRICACAO DE PRODUTOS DIVERSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('324','37.10-9','RECICLAGEM DE SUCATAS METALICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('325','37.20-6','RECICLAGEM DE SUCATAS NAO-METALICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('326','40.11-8','PRODUCAO DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('327','40.12-6','TRANSMISSAO DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('328','40.13-4','COMERCIO ATACADISTA DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('329','40.14-2','DISTRIBUICAO DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('330','40.20-7','PRODUCAO E DISTRIBUICAO DE GAS ATRAVES DE TUBULACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('331','40.30-4','PRODUCAO E DISTRIBUICAO DE VAPOR E AGUA QUENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('332','41.00-9','CAPTACAO, TRATAMENTO E DISTRIBUICAO DE AGUA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('333','45.11-0','DEMOLICAO E PREPARACAO DO TERRENO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('334','45.12-8','SONDAGENS E FUNDACOES DESTINADAS A CONSTRUCAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('335','45.13-6','GRANDES MOVIMENTACOES DE TERRA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('336','45.21-7','EDIFICACOES (RESIDENCIAIS, INDUSTRIAIS, COMERCIAIS E DE SERVICOS)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('337','45.22-5','OBRAS VIARIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('338','45.23-3','OBRAS DE ARTE ESPECIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('339','45.25-0','OBRAS DE MONTAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('340','45.29-2','OBRAS DE OUTROS TIPOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('341','45.31-4','OBRAS PARA GERACAO E DISTRIBUICAO DE ENERGIA ELETRICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('342','45.33-0','OBRAS PARA TELECOMUNICACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('343','45.41-1','INSTALACOES ELETRICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('344','45.42-0','INSTALACOES DE SISTEMAS DE AR CONDICIONADO, DE VENTILACAO E REFRIGERACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('345','45.43-8','INSTALACOES HIDRAULICAS, SANITARIAS, DE GAS E DE SISTEMA DE PREVENCAO CONTRA INCENDIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('346','45.49-7','OUTRAS OBRAS DE INSTALACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('347','45.50-0','OBRAS DE ACABAMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('348','45.60-8','ALUGUEL DE EQUIPAMENTOS DE CONSTRUCAO E DEMOLICAO COM OPERARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('349','50.10-5','COMERCIO A VAREJO E POR ATACADO DE VEICULOS AUTOMOTORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('350','50.20-2','MANUTENCAO E REPARACAO DE VEICULOS AUTOMOTORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('351','50.30-0','COMERCIO A VAREJO E POR ATACADO DE PECAS E ACESSORIOS PARA VEICULOS AUTOMOTORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('352','50.41-5','COMERCIO A VAREJO E POR ATACADO DE MOTOCICLETAS, PARTES, PECAS E ACESSORIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('353','50.42-3','MANUTENCAO E REPARACAO DE MOTOCICLETAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('354','50.50-4','COMERCIO A VAREJO DE COMBUSTIVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('355','51.11-0','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE MATERIAS-PRIMAS AGRICOLAS, ANIMAIS VIVOS, MATERIAS PRIMAS TEXTEIS E PRODUTOS SEMI-ACABADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('356','51.12-8','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE COMBUSTIVEIS, MINERAIS, METAIS E PRODUTOS QUIMICOS INDUSTRIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('357','51.13-6','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE MADEIRA, MATERIAL DE CONSTRUCAO E FERRAGENS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('358','51.14-4','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE MAQUINAS, EQUIPAMENTOS INDUSTRIAIS, EMBARCACOES E AERONAVES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('359','51.15-2','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE MOVEIS E ARTIGOS DE USO DOMESTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('360','51.16-0','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE TEXTEIS, VESTUARIO, CALCADOS E ARTIGOS DE COURO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('361','51.17-9','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE PRODUTOS ALIMENTICIOS, BEBIDAS E FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('362','51.18-7','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO ESPECIALIZADO EM PRODUTOS NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('363','51.19-5','REPRESENTANTES COMERCIAIS E AGENTES DO COMERCIO DE MERCADORIAS EM GERAL (NAO ESPECIALIZADOS)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('364','51.21-7','COMERCIO ATACADISTA DE MATERIAS PRIMAS AGRICOLAS E PRODUTOS SEMI-ACABADOS; PRODUTOS ALIMENTICIOS PARA ANIMAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('365','51.22-5','COMERCIO ATACADISTA DE ANIMAIS VIVOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('366','51.31-4','COMERCIO ATACADISTA DE LEITE E PRODUTOS DO LEITE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('367','51.32-2','COMERCIO ATACADISTA DE CEREAIS BENEFICIADOS E LEGUMINOSAS, FARINHAS, AMIDOS E FECULAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('368','51.33-0','COMERCIO ATACADISTA DE HORTIFRUTIGRANJEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('369','51.34-9','COMERCIO ATACADISTA DE CARNES E PRODUTOS DA CARNE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('370','51.35-7','COMERCIO ATACADISTA DE PESCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('371','51.36-5','COMERCIO ATACADISTA DE BEBIDAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('372','51.37-3','COMERCIO ATACADISTA DE PRODUTOS DO FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('373','51.39-0','COMERCIO ATACADISTA DE OUTROS PRODUTOS ALIMENTICIOS, NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('374','51.41-1','COMERCIO ATACADISTA DE FIOS TEXTEIS, TECIDOS, ARTEFATOS DE TECIDOS E DE ARMARINHO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('375','51.42-0','COMERCIO ATACADISTA DE ARTIGOS DO VESTUARIO E COMPLEMENTOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('376','51.43-8','COMERCIO ATACADISTA DE CALCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('377','51.44-6','COMERCIO ATACADISTA DE ELETRODOMESTICOS E OUTROS EQUIPAMENTOS DE USOS PESSOAL E DOMESTICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('378','51.45-4','COMERCIO ATACADISTA DE PRODUTOS FARMACEUTICOS, MEDICOS, ORTOPEDICOS E ODONTOLOGICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('379','51.46-2','COMERCIO ATACADISTA DE COSMETICOS E PRODUTOS DE PERFUMARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('380','51.47-0','COMERCIO ATACADISTA DE ARTIGOS DE ESCRITORIO E DE PAPELARIA;  LIVROS, JORNAIS, E OUTRAS PUBLICACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('381','51.49-7','COMERCIO ATACADISTA DE OUTROS ARTIGOS DE USOS PESSOAL E DOMESTICO, NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('382','51.51-9','COMERCIO ATACADISTA DE COMBUSTIVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('383','51.52-7','COMERCIO ATACADISTA DE PRODUTOS EXTRATIVOS DE ORIGEM MINERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('384','51.53-5','COMERCIO ATACADISTA DE MADEIRA, MATERIAL DE CONSTRUCAO, FERRAGENS E FERRAMENTAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('385','51.54-3','COMERCIO ATACADISTA DE PRODUTOS QUIMICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('386','51.55-1','COMERCIO ATACADISTA DE RESIDUOS E SUCATAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('387','51.59-4','COMERCIO ATACADISTA DE OUTROS PRODUTOS INTERMEDIARIOS NAO AGROPECUARIOS, NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('388','51.61-6','COMERCIO ATACADISTA DE MAQUINAS, APARELHOS E EQUIPAMENTOS PARA USO AGROPECUARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('389','51.64-0','COMERCIO ATACADISTA DE MAQUINAS E EQUIPAMENTOS PARA O COMERCIO E ESCRITORIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('390','51.65-9','COMERCIO ATACADISTA DE COMPUTADORES,  EQUIPAMENTOS DE TELEFONIA E COMUNICACAO, PARTES E PECAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('391','51.69-1','COMERCIO ATACADISTA DE MAQUINAS, APARELHOS E EQUIPAMENTOS PARA USOS INDUSTRIAL, TECNICO E PROFISSIONAL, E OUTROS USOS, NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('392','51.91-8','COMERCIO ATACADISTA DE MERCADORIAS EM GERAL (NAO ESPECIALIZADO)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('393','51.92-6','COMERCIO ATACADISTA ESPECIALIZADO EM MERCADORIAS NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('394','52.11-6','COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINANCIA DE PRODUTOS ALIMENTICIOS, COM AREA DE VENDA SUPERIOR A 5000 METROS QUADRADOS - HIPERMERCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('395','52.12-4','COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINANCIA DE PRODUTOS ALIMENTICIOS, COM AREA DE VENDA ENTRE 300 E 5000 METROS QUADRADOS - SUPERMERCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('396','52.13-2','COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINANCIA DE PRODUTOS ALIMENTICIOS, COM AREA DE VENDA INFERIOR A 300 METROS QUADRADOS - EXCETO LOJAS DE CONVENIENCIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('397','52.14-0','COMERCIO VAREJISTA DE MERCADORIAS EM GERAL, COM PREDOMINANCIA DE PRODUTOS ALIMENTICIOS INDUSTRIALIZADOS - LOJAS DE CONVENIENCIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('398','52.15-9','COMERCIO VAREJISTA NAO ESPECIALIZADO, SEM PREDOMINANCIA DE PRODUTOS ALIMENTICIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('399','52.21-3','COMERCIO VAREJISTA DE PRODUTOS DE PADARIA, DE LATICINIO, FRIOS E CONSERVAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('400','52.22-1','COMERCIO VAREJISTA DE BALAS, BOMBONS E SEMELHANTES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('401','52.23-0','COMERCIO VAREJISTA DE CARNES - ACOUGUES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('402','52.24-8','COMERCIO VAREJISTA DE BEBIDAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('403','52.29-9','COMERCIO VAREJISTA DE OUTROS PRODUTOS ALIMENTICIOS NAO ESPECIFICADOS ANTERIORMENTE E DE PRODUTOS DO FUMO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('404','52.31-0','COMERCIO VAREJISTA DE TECIDOS E ARTIGOS DE ARMARINHO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('405','52.32-9','COMERCIO VAREJISTA DE ARTIGOS DO VESTUARIO E COMPLEMENTOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('406','52.33-7','COMERCIO VAREJISTA DE CALCADOS, ARTIGOS DE COURO E VIAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('407','52.41-8','COMERCIO VAREJISTA DE PRODUTOS FARMACEUTICOS, ARTIGOS MEDICOS E ORTOPEDICOS, DE PERFUMARIA E COSMETICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('408','52.42-6','COMERCIO VAREJISTA DE MAQUINAS E APARELHOS DE USOS DOMESTICO E PESSOAL, DISCOS E INSTRUMENTOS MUSICAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('409','52.43-4','COMERCIO VAREJISTA DE MOVEIS, ARTIGOS DE ILUMINACAO E OUTROS ARTIGOS PARA RESIDENCIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('410','52.44-2','COMERCIO VAREJISTA DE MATERIAL DE CONSTRUCAO, FERRAGENS E FERRAMENTAS MANUAIS; VIDROS, ESPELHOS E VITRAIS; TINTAS E MADEIRAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('411','52.45-0','COMERCIO VAREJISTA DE EQUIPAMENTOS E MATERIAIS PARA ESCRITORIO; INFORMATICA E COMUNICACAO, INCLUSIVE SUPRIMENTOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('412','52.46-9','COMERCIO VAREJISTA DE LIVROS, JORNAIS, REVISTAS E PAPELARIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('413','52.47-7','COMERCIO VAREJISTA DE GAS LIQUEFEITO DE PETROLEO (GLP)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('414','52.49-3','COMERCIO VAREJISTA DE OUTROS PRODUTOS NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('415','52.50-7','COMERCIO VAREJISTA DE ARTIGOS USADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('416','52.69-8','OUTROS TIPOS DE COMERCIO VAREJISTA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('417','52.71-0','REPARACAO E MANUTENCAO DE MAQUINAS E DE APARELHOS ELETRODOMESTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('418','52.72-8','REPARACAO DE CALCADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('419','52.79-5','REPARACAO DE OUTROS OBJETOS PESSOAIS E DOMESTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('420','55.13-1','ESTABELECIMENTOS HOTELEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('421','55.19-0','OUTROS TIPOS DE ALOJAMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('422','55.21-2','RESTAURANTES E ESTABELECIMENTOS DE BEBIDAS, COM SERVICO COMPLETO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('423','55.22-0','LANCHONETES E SIMILARES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('424','55.23-9','CANTINAS (SERVICOS DE ALIMENTACAO PRIVATIVOS)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('425','55.24-7','FORNECIMENTO DE COMIDA PREPARADA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('426','55.29-8','OUTROS SERVICOS DE ALIMENTACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('427','60.10-0','TRANSPORTE FERROVIARIO INTERURBANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('428','60.21-6','TRANSPORTE FERROVIARIO DE PASSAGEIROS, URBANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('429','60.22-4','TRANSPORTE METROVIARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('430','60.23-2','TRANSPORTE RODOVIARIO DE PASSAGEIROS, REGULAR, URBANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('431','60.24-0','TRANSPORTE RODOVIARIO DE PASSAGEIROS, REGULAR, NAO URBANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('432','60.25-9','TRANSPORTE RODOVIARIO DE PASSAGEIROS, NAO REGULAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('433','60.26-7','TRANSPORTE RODOVIARIO DE CARGAS, EM GERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('434','60.27-5','TRANSPORTE RODOVIARIO DE PRODUTOS PERIGOSOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('435','60.28-3','TRANSPORTE RODOVIARIO DE MUDANCAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('436','60.29-1','TRANSPORTE REGULAR EM BONDES, FUNICULARES, TELEFERICOS OU TRENS PROPRIOS PARA EXPLORACAO DE PONTOS TURISTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('437','60.30-5','TRANSPORTE DUTOVIARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('438','61.11-5','TRANSPORTE MARITIMO DE CABOTAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('439','61.12-3','TRANSPORTE MARITIMO DE LONGO CURSO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('440','61.21-2','TRANSPORTE POR NAVEGACAO INTERIOR DE PASSAGEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('441','61.22-0','TRANSPORTE POR NAVEGACAO INTERIOR DE CARGA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('442','61.23-9','TRANSPORTE AQUAVIARIO URBANO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('443','62.10-3','TRANSPORTE AEREO, REGULAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('444','62.20-0','TRANSPORTE AEREO, NAO REGULAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('445','62.30-8','TRANSPORTE ESPACIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('446','63.11-8','CARGA E DESCARGA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('447','63.12-6','ARMAZENAMENTO E DEPOSITOS DE CARGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('448','63.21-5','ATIVIDADES AUXILIARES DOS TRANSPORTES TERRESTRES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('449','63.22-3','ATIVIDADES AUXILIARES DOS TRANSPORTES AQUAVIARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('450','63.23-1','ATIVIDADES AUXILIARES DOS TRANSPORTES AEREOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('451','63.30-4','ATIVIDADES DE AGENCIAS DE VIAGENS E ORGANIZADORES DE VIAGEM');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('452','63.40-1','ATIVIDADES RELACIONADAS A ORGANIZACAO DO TRANSPORTE DE CARGAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('453','64.11-4','ATIVIDADES DE CORREIO NACIONAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('454','64.12-2','ATIVIDADES DE MALOTE E ENTREGA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('455','64.20-3','TELECOMUNICACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('456','65.10-2','BANCO CENTRAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('457','65.21-8','BANCOS COMERCIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('458','65.22-6','BANCOS MULTIPLOS (COM CARTEIRA COMERCIAL)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('459','65.23-4','CAIXAS ECONOMICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('460','65.24-2','CREDITO COOPERATIVO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('461','65.31-5','BANCOS MULTIPLOS (SEM CARTEIRA COMERCIAL)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('462','65.32-3','BANCOS DE INVESTIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('463','65.33-1','BANCOS DE DESENVOLVIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('464','65.34-0','CREDITO IMOBILIARIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('465','65.35-8','SOCIEDADES DE CREDITO, FINANCIAMENTO E INVESTIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('466','65.40-4','ARRENDAMENTO MERCANTIL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('467','65.51-0','AGENCIAS DE FOMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('468','65.59-5','OUTRAS ATIVIDADES DE CONCESSAO DE CREDITO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('469','65.91-9','FUNDOS DE INVESTIMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('470','65.92-7','SOCIEDADES DE CAPITALIZACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('471','65.93-5','GESTAO DE ATIVOS INTANGIVEIS NAO FINANCEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('472','65.99-4','OUTRAS ATIVIDADES DE INTERMEDIACAO FINANCEIRA, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('473','66.11-7','SEGUROS DE VIDA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('474','66.12-5','SEGUROS NAO-VIDA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('475','66.13-3','RESSEGUROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('476','66.21-4','PREVIDENCIA COMPLEMENTAR FECHADA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('477','66.22-2','PREVIDENCIA COMPLEMENTAR ABERTA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('478','67.11-3','ADMINISTRACAO DE MERCADOS BURSATEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('479','67.12-1','ATIVIDADES DE INTERMEDIARIOS EM TRANSACOES DE TITULOS E VALORES MOBILIARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('480','67.19-9','OUTRAS ATIVIDADES AUXILIARES DA INTERMEDIACAO FINANCEIRA, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('481','67.20-2','ATIVIDADES AUXILIARES DOS SEGUROS E DA PREVIDENCIA COMPLEMENTAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('482','70.10-6','INCORPORACAO E COMPRA E VENDA DE IMOVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('483','70.20-3','ALUGUEL DE IMOVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('484','70.31-9','CORRETAGEM E AVALIACAO DE IMOVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('485','70.32-7','ADMINISTRACAO DE IMOVEIS POR CONTA DE TERCEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('486','70.40-8','CONDOMINIOS PREDIAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('487','71.10-2','ALUGUEL DE AUTOMOVEIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('488','71.21-8','ALUGUEL DE OUTROS MEIOS DE TRANSPORTE TERRESTRE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('489','71.22-6','ALUGUEL DE EMBARCACOES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('490','71.23-4','ALUGUEL DE AERONAVES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('491','71.31-5','ALUGUEL DE MAQUINAS E EQUIPAMENTOS AGRICOLAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('492','71.32-3','ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA CONSTRUCAO E ENGENHARIA CIVIL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('493','71.33-1','ALUGUEL DE MAQUINAS E EQUIPAMENTOS PARA ESCRITORIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('494','71.39-0','ALUGUEL DE MAQUINAS E EQUIPAMENTOS DE OUTROS TIPOS, NAO ESPECIFICADOS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('495','71.40-4','ALUGUEL DE OBJETOS PESSOAIS E DOMESTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('496','72.10-9','CONSULTORIA EM HARDWARE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('497','72.21-4','DESENVOLVIMENTO E EDICAO DE SOFTWARES PRONTOS PARA USO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('498','72.29-0','DESENVOLVIMENTO DE SOFTWARES SOB ENCOMENDA E OUTRAS CONSULTORIAS EM SOFTWARE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('499','72.30-3','PROCESSAMENTO DE DADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('500','72.40-0','ATIVIDADES DE BANCO DE DADOS E DISTRIBUICAO ON-LINE DE CONTEUDO ELETRONICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('501','72.50-8','MANUTENCAO E REPARACAO DE MAQUINAS DE ESCRITORIO E DE INFORMATICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('502','72.90-7','OUTRAS ATIVIDADES DE INFORMATICA, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('503','73.10-5','PESQUISA E DESENVOLVIMENTO DAS CIENCIAS FISICAS E NATURAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('504','73.20-2','PESQUISA E DESENVOLVIMENTO DAS CIENCIAS SOCIAIS E HUMANAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('505','74.11-0','ATIVIDADES JURIDICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('506','74.12-8','ATIVIDADES DE CONTABILIDADE E AUDITORIA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('507','74.14-4','GESTAO DE PARTICIPACOES SOCIETARIAS (HOLDINGS)');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('508','74.15-2','SEDES DE EMPRESAS E UNIDADES ADMINISTRATIVAS LOCAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('509','74.16-0','ATIVIDADES DE ASSESSORIA EM GESTAO EMPRESARIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('510','74.20-9','SERVICOS DE ARQUITETURA E ENGENHARIA E DE ASSESSORAMENTO TECNICO ESPECIALIZADO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('511','74.30-6','ENSAIOS DE MATERIAIS E DE PRODUTOS; ANALISE DE QUALIDADE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('512','74.40-3','PUBLICIDADE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('513','74.50-0','SELECAO, AGENCIAMENTO E LOCACAO DE MAO-DE-OBRA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('514','74.60-8','ATIVIDADES DE INVESTIGACAO, VIGILANCIA E SEGURANCA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('515','74.70-5','ATIVIDADES DE IMUNIZACAO, HIGIENIZACAO E DE LIMPEZA EM PREDIOS E EM DOMICILIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('516','74.91-8','ATIVIDADES FOTOGRAFICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('517','74.92-6','ATIVIDADES DE ENVASAMENTO E EMPACOTAMENTO, POR CONTA DE TERCEIROS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('518','74.99-3','OUTRAS ATIVIDADES DE SERVICOS PRESTADOS PRINCIPALMENTE AS EMPRESAS, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('519','75.12-4','REGULACAO DAS ATIVIDADES SOCIAIS E CULTURAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('520','75.13-2','REGULACAO DAS ATIVIDADES ECONOMICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('521','75.14-0','ATIVIDADES DE APOIO A ADMINISTRACAO PUBLICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('522','75.21-3','RELACOES EXTERIORES');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('523','75.22-1','DEFESA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('524','75.23-0','JUSTICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('525','75.24-8','SEGURANCA E ORDEM PUBLICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('526','75.25-6','DEFESA CIVIL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('527','75.30-2','SEGURIDADE SOCIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('528','80.13-6','EDUCACAO INFANTIL-CRECHE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('529','80.14-4','EDUCACAO INFANTIL-PRE-ESCOLA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('530','80.15-2','ENSINO FUNDAMENTAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('531','80.20-9','ENSINO MEDIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('532','80.31-4','EDUCACAO SUPERIOR - GRADUACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('533','80.32-2','EDUCACAO SUPERIOR - GRADUACAO E POS-GRADUACAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('534','80.33-0','EDUCACAO SUPERIOR - POS-GRADUACAO E EXTENSAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('535','80.96-9','EDUCACAO PROFISSIONAL DE NIVEL TECNICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('536','80.97-7','EDUCACAO PROFISSIONAL DE NIVEL TECNOLOGICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('537','80.99-3','OUTRAS ATIVIDADES DE ENSINO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('538','85.11-1','ATIVIDADES DE ATENDIMENTO HOSPITALAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('539','85.12-0','ATIVIDADES DE ATENDIMENTO A URGENCIAS E EMERGENCIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('540','85.13-8','ATIVIDADES DE ATENCAO AMBULATORIAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('541','85.14-6','ATIVIDADES DE SERVICOS DE COMPLEMENTACAO DIAGNOSTICA OU TERAPEUTICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('542','85.15-4','ATIVIDADES DE OUTROS PROFISSIONAIS DA AREA DE SAUDE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('543','85.16-2','OUTRAS ATIVIDADES RELACIONADAS COM A ATENCAO A SAUDE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('544','85.20-0','SERVICOS VETERINARIOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('545','85.31-6','SERVICOS SOCIAIS COM ALOJAMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('546','85.32-4','SERVICOS SOCIAIS SEM ALOJAMENTO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('547','90.00-0','LIMPEZA URBANA E ESGOTO E ATIVIDADES RELACIONADAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('548','91.11-1','ATIVIDADES DE ORGANIZACOES EMPRESARIAIS E PATRONAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('549','91.12-0','ATIVIDADES DE ORGANIZACOES PROFISSIONAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('550','91.20-0','ATIVIDADES DE ORGANIZACOES SINDICAIS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('551','91.91-0','ATIVIDADES DE ORGANIZACOES RELIGIOSAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('552','91.92-8','ATIVIDADES DE ORGANIZACOES POLITICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('553','91.99-5','OUTRAS ATIVIDADES ASSOCIATIVAS, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('554','92.11-8','PRODUCAO DE FILMES CINEMATOGRAFICOS E FITAS DE VIDEO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('555','92.12-6','DISTRIBUICAO DE FILMES E DE VIDEOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('556','92.13-4','PROJECAO DE FILMES E DE VIDEOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('557','92.21-5','ATIVIDADES DE RADIO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('558','92.22-3','ATIVIDADES DE TELEVISAO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('559','92.32-0','GESTAO DE SALAS DE ESPETACULOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('560','92.39-8','OUTRAS ATIVIDADES DE ESPETACULOS, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('561','92.40-1','ATIVIDADES DE AGENCIAS DE NOTICIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('562','92.51-7','ATIVIDADES DE BIBLIOTECAS E ARQUIVOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('563','92.52-5','ATIVIDADES DE MUSEUS E DE CONSERVACAO DO PATRIMONIO HISTORICO');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('564','92.53-3','ATIVIDADES DE JARDINS BOTANICOS, ZOOLOGICOS, PARQUES NACIONAIS E RESERVAS ECOLOGICAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('565','92.61-4','ATIVIDADES DESPORTIVAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('566','92.62-2','OUTRAS ATIVIDADES RELACIONADAS AO LAZER');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('567','93.01-7','LAVANDERIAS E TINTURARIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('568','93.02-5','CABELEIREIROS E OUTROS TRATAMENTOS DE BELEZA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('569','93.03-3','ATIVIDADES FUNERARIAS E SERVICOS RELACIONADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('570','93.04-1','ATIVIDADES DE MANUTENCAO DO FISICO CORPORAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('571','93.09-2','OUTRAS ATIVIDADES DE SERVICOS PESSOAIS, NAO ESPECIFICADAS ANTERIORMENTE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('572','95.00-1','SERVICOS DOMESTICOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('573','75.11-6','ADMINISTRACAO PUBLICA EM GERAL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('574','05.12-6','AGRICULTURA E SERVICOS RELACIONADOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('575','15.61-0','USINAS DE ACUCAR');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('576','15.72-5','FABRICACAO DE CAFE SOLUVEL');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('577','66.30-3','PLANOS DE SAUDE');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('578','92.31-2','ATIVIDADES DE TEATRO, MUSICA E OUTRAS ATIVIDADES ARTISTICAS E LITERARIAS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('579','74.13-6','PESQUISAS DE MERCADO E DE OPINIAO PUBLICA');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('580','52.62-0','COMERCIO EM VIAS PUBLICAS, EXCETO EM QUIOSQUES FIXOS');
INSERT INTO dbsinan.tb_cnae (co_seq_cnae, nu_classe_cnae, ds_cnae) VALUES ('581','01.13-9','CULTIVO DE CANA-DE ACUCAR');

