insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (9,'Shigella sp');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (10,'Staphylococcus (aureus, sp, epidermidis)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (11,'Salmonella sp');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (12,'Escherichia coli');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (13,'Klebsiella (sp, pneumoniae)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (14,'Streptococcus (sp, pyogenes, agalactiae)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (15,'Enterococcus');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (16,'Pseudomonas (aeruginosa, sp)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (18,'Serratia (marcescens, sp)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (19,'Alcaligenes (sp, faecalis)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (20,'Proteus (sp, vulgaris, mirabilis)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (21,'Listeria monocytogenes');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (22,'Enterobacter (sp, cloacae)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (23,'Acinetobacter (sp, baumannii)');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (26,'Neisseria sp');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (28,'Outras Bacterias');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (45,'Treponema Pallidum');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (46,'Rickettsiae');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (49,'Leptospira');
insert into dbsinan.tb_meningite_bacteria (co_seq_bacteria, ds_bacteria) values (81,'Bacteria nao especificada');
