insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	1,'0,0-DIETIL-0-FENIL FOSFOROTIOATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	2,'2,4 - D'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	3,'2,4 D'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	4,'2,4 D+PICLORAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	5,'2,4-D ESTER BUTILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	6,'2,4-D ESTER BUTILICO do ACIDO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	7,'2,4-D SAL DIMETILAMINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	8,'ABAMECTIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	9,'ABAMECTIN NORTOX'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	10,'ABAMECTINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	11,'ACEFATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	12,'ACEPHATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	13,'ACETACHLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	14,'ACETAMIPRID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	15,'ACETAMIPRIDO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	16,'ACETATO de (E,Z)-3,8 TETRADECADIENILA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	17,'ACETOCHLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	18,'ACETOCLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	19,'ACIBENZOLAR S-METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	20,'ACIDO GIBERELICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	21,'ACIDO4-INDOL-3-ILBUTIRICO+ACIDO GIBERELICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	22,'ACIFLUORFEN SAL DE SODIO + BENTAZON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	23,'ACIFLUORFEN SAL DE SODIO+BENTAZON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	24,'ACIFLUORFEN SODIUM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	25,'ACRINATHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	26,'ALACHLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	27,'ALACHLOR + ATRAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	28,'ALACHLOR+ATRAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	29,'ALCOOLFENOIS, OXIDO DE ETENO, SULFONATOS ORGANICOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	30,'ALDICARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	31,'ALFACIPERMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	32,'ALQUIL ESTER ETOXILADO DO ACIDO FOSFORICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	33,'ALQUIL FENOL POLIGLICOLETER'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	34,'AMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	35,'AMETRINA+SIMAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	36,'AMETRYNE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	37,'AMETRYNE+DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	38,'AMITRAZ'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	39,'ANILAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	40,'ATRAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	41,'ATRAZINA+SIMAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	42,'ATRAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	43,'ATRAZINE+IMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	44,'ATRAZINE+SIMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	45,'AZAFENIDIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	46,'AZAFENIDIN+HEXAZINONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	47,'AZINSULFUROM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	48,'AZOCYCLOTIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	49,'AZOXYSTROBIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	50,'AZOXYSTROBIN + CYPROCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	51,'BACILLUS THURINGIENSIS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	52,'BACILLUS THURINGIENSIS AIZAWAI GC-91'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	53,'BACULOVIRUS ANTICARSIA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	54,'BENALAXYL + MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	55,'BENTAZON S SODICO+ACIFLUORFEN SODIUM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	56,'BENTAZON SAL SODICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	57,'BENTAZONE, SAL SODICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	58,'BENZILADENINA + ACIDO GIBERELICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	59,'BETA - CYPERMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	60,'BETA-CIFLUTRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	61,'BETA-CYFLUTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	62,'BETACYFLUTRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	63,'BIFENTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	64,'BIFENTRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	65,'BISPYRIBAC-SODIUM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	66,'BITERTANOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	67,'BROMACILA +DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	68,'BROMETO DE METILA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	69,'BROMOPROPYLATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	70,'BROMUCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	71,'BUPROFEZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	72,'BUTRALIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	73,'BUTROXYDIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	74,'CADUSAFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	75,'CAPTAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	76,'CAPTAN+DERIV CORRELATOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	77,'CARBARYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	78,'CARBENDAZIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	79,'CARBENDAZIM+THIRAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	80,'CARBOFURAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	81,'CARBOSULFAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	82,'CARBOSULFAN+ZINCO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	83,'CARBOXIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	84,'CARBOXIN+THIRAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	85,'CARFENTRAZONE-ETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	86,'CARTAP CLORIDRATO+INGREDIENTE INERTE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	87,'CARTAP, CLORIDRATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	88,'CASUGAMICINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	89,'CETOENOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	90,'CHLORFENAPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	91,'CHLORIMURON ETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	92,'CHLORIMURONETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	93,'CHLOROTHALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	94,'CHLOROTHALONIL+OXICLORETO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	95,'CHLOROTHALONIL+THIOPHANATE METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	96,'CHLORPYRIFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	97,'CHLORTHAL-DIMETHHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	98,'CIANAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	99,'CICLOSSULFAMURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	100,'CIPERMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	101,'CIPRODINIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	102,'CLETHODIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	103,'CLOMAZONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	104,'CLOMAZONE + AMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	105,'CLORANSULAM METIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	106,'CLORETO DE ALQUIL DIMETIL BENZIL AMONIA+P-NONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	107,'CLORETO DE CLORMEQUAT'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	108,'CLORETO DE MEPIQUAT'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	109,'CLORETO DE MEPIQUATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	110,'CLORFLUAZURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	111,'CLORIDRATO DE AVEGLICINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	112,'CLORIMURON ETIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	113,'CLOROFENTEZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	114,'CLOROTALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	115,'CLOROTALONIL E CARBENDAZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	116,'CLORPIRIFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	117,'CLOTHIANIDIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	118,'CODLELURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	119,'COPOLIMERO DE POLIETER E SILICONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	120,'CRESOXIN METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	121,'CUPRICOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	122,'CYANAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	123,'CYANAZINE+SIMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	124,'CYCLANILIDE e ETHEPHON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	125,'CYFLUTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	126,'CYHEXATIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	127,'CYMOXANIL+FAMOXADONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	128,'CYMOXANIL+MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	129,'CYMOXANIL+MANEB+SULFATO DE ZINCO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	130,'CYPERMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	131,'CYPERMETHRIN+PROFENOFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	132,'CYPERMETRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	133,'CYPROCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	134,'CYPROCONAZOLE+DISULFOTON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	135,'CYPROCONAZOLE+OXICLORETO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	136,'CYROMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	137,'DAZOMET'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	138,'DECANOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	139,'DELTAMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	140,'DELTAMETHRIN+ENDOSULFAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	141,'DELTAMETHRIN+TRIAZOPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	142,'DELTAMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	143,'DIAFENTIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	144,'DIAZINON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	145,'DIBROMETO DE DIQUATE+DICLORETO DE PARA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	146,'DICLOFOP-METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	147,'DICLOSULAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	148,'DICOFOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	149,'DICOFOL+TETRADIFON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	150,'DIFENOCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	151,'DIFLUBENZURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	152,'DIMETHENAMID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	153,'DIMETHENAMID+ATRAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	154,'DIMETHOATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	155,'DIMETHOMORPH'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	156,'DINOCAPE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	157,'DIQUAT'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	158,'DISULFOTON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	159,'DITHIANON (DITIANONA)'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	160,'DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	161,'DIURON MSMA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	162,'DIURON+HEXAZINONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	163,'DIURON+TEBUTHIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	164,'DODINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	165,'DODINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	166,'EDIPHENPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	167,'ENDOSSULFAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	168,'ENDOSULFAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	169,'ENXOFRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	170,'EPOXICONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	171,'ESFENVALERATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	172,'ESFENVALERATO+FENITROTIONA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	173,'ESPALHANTE ADESIVO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	174,'ESPIRODICLOFENO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	175,'ESTER ACIDO GRAXO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	176,'ESTERES DE ACIDO GRAXO COM GLICEROL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	177,'ESTERES DO ACIDO GRAXO COM GLICEROL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	178,'ESTERES DO ACIDO SULFUROSO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	179,'ETHEPHON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	180,'ETHEPHON+GLUFOSINATO DE AMONIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	181,'ETHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	182,'ETHOPROPOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	183,'ETIL-TRINEXAPAC'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	184,'ETOFENPROX'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	185,'ETRIDIAZOLIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	186,'FAMOXADONE+MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	187,'FENAMIDONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	188,'FENAMIFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	189,'FENAMIPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	190,'FENARIMOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	191,'FENBUTATIN OXIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	192,'FENITROTHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	193,'FENITROTION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	194,'FENITROTION+ESFENVALERATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	195,'FENOXAPROPE-P-ETILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	196,'FENOXAPROP-P-ETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	197,'FENOXAPROP-P-ETHYL+CLETHODIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	198,'FENOXAPROP-P-ETIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	199,'FENPIROXIMATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	200,'FENPROPATHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	201,'FENPROPIMORPH'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	202,'FENPYROXIMATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	203,'FENTHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	204,'FENTIN ACETATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	205,'FENTIN HIDROXIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	206,'FENTOATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	207,'FENVALERATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	208,'FIPRONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	209,'FLAZASSULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	210,'FLUAZIFOP P.+ FOMESAFEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	211,'FLUAZIFOP-P-BUTIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	212,'FLUAZINAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	213,'FLUDIOXONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	214,'FLUDIOXONIL+METALAXYL-M'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	215,'FLUMETRALIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	216,'FLUMETSULAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	217,'FLUMICLORAC-PENTIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	218,'FLUMIOXAZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	219,'FLUQUINCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	220,'FLUROXIPIR MHE + PICLORAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	221,'FLUTRIAFOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	222,'FLUVALINATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	223,'FLUXOPIR MHE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	224,'FOLPET'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	225,'FOMESAFEM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	226,'FOMESAFEM+FLUAZITOP-P-BUTIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	227,'FORAMSULFUROM+IODOSULFURON-METHYL-SODIUM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	228,'FORATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	229,'FORMETANATE HIDROCLORETO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	230,'FOSETYL-AL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	231,'FOSF DE MAGNES+EQUIVAL EM FOSFINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	232,'FOSFETO DE ALUMINIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	233,'FOSMETE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	234,'FURATHIOCARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	235,'GIBERELINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	236,'GLIFOSATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	237,'GLIFOSATE POTASSICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	238,'GLIFOSATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	239,'GLOSSIPLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	240,'GLUFOSINATO DE AMONIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	241,'GLYPHOSATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	242,'GLYPHOSATE, ISOPROPAL+DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	243,'GLYPHOSATE, ISOPROPALAMINA+SIMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	244,'GLYPHOSATE, ISOPROPILAMINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	245,'GRANDLURE(5,7)+MALATHION(372)'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	246,'HALOSULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	247,'HALOXIFOPE P-METIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	248,'HEXACONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	249,'HEXACONAZOLE+CHLOROTHALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	250,'HEXAZINONA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	251,'HEXAZINONA+DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	252,'HEXAZINONE+DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	253,'HEXTHIAZOX'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	254,'HIDRAZIDA MALEICA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	255,'HIDROCARBONETO AROMATICO, ESTERES METILICOS E POLIOL FOSFATADO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	256,'HIDROXICO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	257,'HIDROXIDO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	258,'IMAZALIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	259,'IMAZAMOX'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	260,'IMAZAPIC e IMAZAPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	261,'IMAZAPIQUE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	262,'IMAZAPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	263,'IMAZAQUIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	264,'IMAZAQUIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	265,'IMAZAQUIN + METRIBUZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	266,'IMAZETHAPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	267,'IMAZETHAPYR+GLIFOSATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	268,'IMIBENCONAZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	269,'IMIDACLOPRID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	270,'IMIDACLOPRID+CYFLUTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	271,'IMIDACLOPRIDO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	272,'INDOXACARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	273,'IODOSULFURON - METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	274,'IOXYMIL OCTANATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	275,'IPRODIONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	276,'IPROVALICARB+PROPINEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	277,'ISOXAFLUTOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	278,'ISOXAFLUTOLE+ATRAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	279,'LACTOFEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	280,'LAMBDACYHALOTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	281,'LAMBDACYHALOTRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	282,'LAURIL ETER SULF DE SODIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	283,'LINURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	284,'LUFENURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	285,'MALATHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	286,'MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	287,'MANCOZEB + CYMOXANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	288,'MANCOZEB+THIOPHANATE METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	289,'MESOTRIONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	290,'METALAXYL-M+CHLOROTALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	291,'METALAXYL-M+MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	292,'METAMIDOFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	293,'METAMITRON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	294,'METCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	295,'METHAMIDOPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	296,'METHIDATION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	297,'METHOMYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	298,'METHOXYFENOZIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	299,'METIDATIONA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	300,'METILCARBAMATO DE BENZOFURALINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	301,'METILCICLOPROPENO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	302,'METIOCARBE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	303,'METIRAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	304,'METIRAM + PYRACLOSTROBIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	305,'METOLACLORO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	306,'METOLACLORO+ATRAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	307,'METRIBUZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	308,'METRIBUZIN+IMAZAQUIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	309,'METSULFURON METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	310,'MOLINATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	311,'MOLINATE+PROPANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	312,'MONOCROTOFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	313,'MSMA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	314,'MYCLOBUTANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	315,'N-2S-METILBUTIL-2-METILBUTILAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	316,'NAPRONAMIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	317,'NAVALURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	318,'NICOSSULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	319,'NICOSULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	320,'NONIL FENOX POL ETANOL+SOD DODEC BENZ SULF'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	321,'NONIL FENOXI POLIETANOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	322,'NONILFENOL OXIETILADO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	323,'NONILFENOL OXIETILADO+ALCOOL ISOPROPILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	324,'NONILFENOL-POLIGLICOLETER'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	325,'OLEO MINERAL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	326,'OLEO VEGETAL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	327,'OMETHOATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	328,'ORIZALINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	329,'OXADIAZON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	330,'OXICLORETO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	331,'OXICLORETO DE COBRE+MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	332,'OXIDO CUPROSO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	333,'OXITETRACICLINA+SULF DE ESTREPTOMICINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	334,'OXITETRACICLINA+TERRAMICINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	335,'OXYCARBOXIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	336,'OXYFLUORFEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	337,'PARAQUAT'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	338,'PARAQUAT+BENTAZONA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	339,'PARAQUAT+DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	340,'PARATHION METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	341,'PARATHION METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	342,'PARATION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	343,'PENCYCURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	344,'PENDIMETALINA+IMAZAQUIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	345,'PENDIMETHALIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	346,'PERMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	347,'PERMETHRYN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	348,'PERMETHYN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	349,'PERMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	350,'PHORATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	351,'PICLORAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	352,'PICLORAN, SAL TRIETANOL+2,4-D, SAL TRIETANOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	353,'PIRAZOSSULFUROM-ETILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	354,'PIRIMICARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	355,'PIRIMIPHOS-METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	356,'PIROPROXIFEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	357,'POLIETER POLIMETIL SILOXANO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	358,'POLIOXIETILENO ALQUIL FENOL ETER'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	359,'POLI-OXIETILENO-ALQUIL-FENOL-ESTER'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	360,'POOMETRYNE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	361,'PROCHLORAZ'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	362,'PROCIMIDONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	363,'PROCLORAZ'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	364,'PROFENOFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	365,'PROFENOFOS+LUFENURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	366,'PROPAMOCARB HYDROCHLORIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	367,'PROPAMOCARB HYDROCHLORIDE+CHLOROTHALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	368,'PROPANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	369,'PROPANIL+2,4-D, EST BUTIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	370,'PROPANIL+TRICLOPIR-BUTOTILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	371,'PROPAQUIZAFOP'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	372,'PROPARAGITE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	373,'PROPARGITE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	374,'PROPARGITO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	375,'PROPICONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	376,'PROPICONAZOLE+CYPROCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	377,'PROPINEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	378,'PROTIOFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	379,'PYRACLOSTROBIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	380,'PYRACLOSTROBIN+EPOXICONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	381,'PYRAZOPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	382,'PYRIDABEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	383,'PYRIDAPHENTHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	384,'PYRIMETHANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	385,'PYRITHIOBAC-SODIUM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	386,'PYROQUILON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	387,'QUINOMETHIONATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	388,'QUINTOZENE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	389,'QUINTOZENO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	390,'QUIZALOFOP-P-ETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	391,'QUIZALOFOP-P-ETIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	392,'QUIZALOFOP-P-TEFURIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	393,'RESINA SINTETICA EMULS+AG TENSO ATIV ANIONICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	394,'RINCOFOROL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	395,'SAL DE AMONIO GLIFOSATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	396,'SAL DIMETILAMINA DO ACIDO 2,4-D'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	397,'SAL DIMETILAMINA MCPA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	398,'SERRICORNIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	399,'SETHOXYDIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	400,'SIMAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	401,'SIMAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	402,'SIMAZINE+AMETRYNE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	403,'S-METOLACLORO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	404,'S-METOLACLORO + ATRAZINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	405,'SPINOSAD'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	406,'SULFATO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	407,'SULFENTRAZONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	408,'SULFLURAMID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	409,'SULFLURAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	410,'SULFOMETURON METIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	411,'SULFOSATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	412,'SULFOSATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	413,'SULPHUR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	414,'TEBUCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	415,'TEBUCONAZOLE + TRIADIMENOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	416,'TEBUFENOZIDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	417,'TEBUTHIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	418,'TEBUTIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	419,'TEFLUBENZURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	420,'TEPRALOXYDIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	421,'TERBUFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	422,'TERRA DIATOMACEA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	423,'TETRACONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	424,'TETRADIFON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	425,'THIABENDAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	426,'THIACLOPRID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	427,'THIAMETHOXAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	428,'THIAMETHOXAM+CYPROCONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	429,'THIAMETOXAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	430,'THIAMETOXAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	431,'THIDIAZURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	432,'THIDIAZURON e DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	433,'THIOBENCARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	434,'THIOBENCARB+PROPANIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	435,'THIODICARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	436,'THIOMETHOXAM+CYPERMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	437,'THIOPHANATE METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	438,'THIOPHANATE METHYL+CHLOROTHAL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	439,'THIRAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	440,'THIRAM E THIABENDAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	441,'TIAZOPIR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	442,'TIOFANATO METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	443,'TIOFANATOMETILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	444,'TIRAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	445,'TOLYLFLUANID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	446,'TRIADIMEFON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	447,'TRIADIMENOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	448,'TRIADIMENOL+DISULFOTON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	449,'TRIAZINA +CLOROACETANILIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	450,'TRIAZOPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	451,'TRICHLORFON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	452,'TRICLOPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	453,'TRICYCLAZOLE+REAX 45 L+LAURIL SULF SOD ZEOLOEX 7+BARDEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	454,'TRIFLOXISTROBIN+PROPICONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	455,'TRIFLOXISTROBINA + CIPROCONAZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	456,'TRIFLUMIZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	457,'TRIFLUMURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	458,'TRIFLURALIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	459,'TRIFLURALIN+IMAZAQUIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	460,'TRIFLURALINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	461,'TRIFLUXYSULFURON SIDIUM+AMETRINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	462,'TRIFLUZAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	463,'TRIFORINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	464,'TRITICONAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	465,'VINCLOSOLINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	466,'ZETACYPERMETHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	467,'ZOXAMIDE+MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	468,'ACEBENZOLAR S-METHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	469,'ACEFATO INSATURADO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	470,'ACIDO SULFONICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	471,'ALFA-CIPERMETRIN + TEFLUBENZURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	472,'AMICARBAZONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	473,'AMINOPYLARID/FLUROXIPIR-MEPTILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	474,'ASULAN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	475,'BIFENTHRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	476,'BOSCALID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	477,'MISTURA DE POLIMERO COM ALCOOL ALIFATICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	478,'BOSCALID+CRESOXIM-METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	479,'BUTACHLON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	480,'BUTYLATE + ATRAZINE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	481,'CARBENDAZIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	482,'CARPROPAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	483,'CHLORFENVINPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	484,'CHLORFENVIPHOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	485,'CHLORIMURON ETHYL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	486,'CHLOROTHALONIL+OXICLORETO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	487,'CLEFOXYDIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	488,'CLOMAZONE +HEXAZINONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	489,'CLORETO DE BENZALCONIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	490,'CLORIDRATO DE PROPAMO CABRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	491,'CLORPIRIFOS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	492,'CLOTHIANIDIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	493,'CYHALOFOP BUTIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	494,'CYMOXANIL+ CHLOROTHALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	495,'DIMETHOMORPH+CLOROTHALONIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	496,'DIURON (HERB. DERIVADO DA UREIA)'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	497,'DIURON / BROMACIL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	498,'EPTC'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	499,'ESPIRO MESIFENO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	500,'ESPNOSADE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	501,'ESTER METILICO DE OLEO DE SOJA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	502,'ETHOXYSULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	503,'FENVALERATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	504,'FITALIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	505,'FLOCOUMARINAS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	506,'FLUFENOXURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	507,'FLUQUINEONAZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	508,'FLURIDONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	509,'FLUTRIAFOL+TIOFANATO-METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	510,'FLUTRIAFOL+TIOFANATO-METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	511,'FOSFETO DE MAGNESIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	512,'GAMMA CYHALOTRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	513,'GAMMA CYHALOTRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	514,'GAMMA CYHALOTRIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	515,'GLYPHOSATE + 2,4-D'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	516,'GOSSYPLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	517,'GOSSYPLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	518,'GRANDLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	519,'GRANDLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	520,'GRANDLURE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	521,'HALOXIFOP - R , ESTER METILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	522,'HEPTACHLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	523,'HEPTACHLOR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	524,'HIDROXIDO DE COBRE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	525,'IMAZAPYR'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	526,'IMAZETHAPYR+IMAZAPIC'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	527,'IMIDACLO PRID+THIODICARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	528,'IMINOCTADINATRIS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	529,'INAZETHAPYR + GLIFOSATO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	530,'INDOXACARB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	531,'ISOURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	532,'KASUGAMYCIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	533,'LATEX SINTETICO E FLUIDO ORGANOSILICONE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	534,'MANCOZEB+DIMETOMORPH'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	535,'METALAXYL + MANCOZEB'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	536,'METALDEHYDE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	537,'METOLACHLOR + METRIBUZIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	538,'MILBEMECTIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	539,'MISTURA DE SULFATO DE AMONIO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	540,'N- (FOSFONOMETIL) GLICINA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	541,'NALED'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	542,'NONIL FENOL ETOXILADO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	543,'NORFLURAZON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	544,'OXASULFURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	545,'PENOXSULAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	546,'PHOSPHAIDY LCOLINE+ACIDO PROPIONICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	547,'PHOSTEBUPIRIM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	548,'PICOXYSTRO BIN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	549,'PIRAFLUFEM-ETILICO'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	550,'PROPARGITE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	551,'PROPICONAZOL + DIFENOCONAZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	552,'PROPARGITE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	553,'PYRIDATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	554,'PROPARGITE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	555,'PYRIPROXIFEN'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	556,'SAL DE ISOPROPILAMINA DE GLIFOSATE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	557,'SAL TRIISOPROPANOLAMINA DO 2,4-D+TRIISOPROPANOLAMINA DO PICLORAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	558,'SULFONAMIDAS FLUOROALIFATICAS'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	559,'THEBUTHIURON + DIURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	560,'THIACLOPRID'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	561,'THIOMETON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	562,'TRICYCLAZOLE'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	563,'TRIFLOXISTROBINA+TEBUCONAZOL'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	564,'TRIFLUMURON'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	565,'VAMIDATHION'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	566,'ZIRAM'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	567,'CIAZOFAMIDA'	)	;
insert into dbsinan.tb_exogena_agro_principio (co_seq_agro_principio,ds_agro_principio) values 	(	568,'OUTROS PRINCIPIOS'	)	;                                              
