INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(1,'SITIO','SIT')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(2,'FAZENDA','FAZ')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(3,'BAIRRO','BAIR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(4,'POVOADO','POVO')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(5,'VILA','VILA')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(6,'NUCLEO','NUCL')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(7,'CIDADE;SEDE MUNICIPAL','CID')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(8,'USINA','USIN')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(9,'CONJUNTO HABITACIONAL','CONJ')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(10,'ENGENHO','ENGE')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(11,'ACAMPAMENTO','ACAM')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(12,'MALOCA','MALO')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(13,'SERRARIA','SERR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(14,'QUADRA','QUAD')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(15,'QUARTEIRAO','QUAR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(16,'BLOCO DE APARTAMENTO','BLOC')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(17,'GARIMPO','GARI')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(18,'CEMITERIO','CEMI')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(19,'CASA ISOLADA','CASA')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(20,'PRACA;PARQUE','PRAC')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(21,'IGREJA;TEMPLO','IGRE')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(22,'AEROPORTO','AERO')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(23,'ESTADIOS;GINASIOS','ESTA')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(24,'CLUBE','CLUB')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(25,'RODOVIARIA;FERROVIARIA','RODO')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(26,'COLONIAL','COL')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(27,'SERINGAL','SER')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(28,'GLEBA','GLE')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(29,'ALDEIA','ALD')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(30,'RAMAL','RAM')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(31,'PROJETO','PROJ')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(32,'PROJETO ASSENTADO DIRIGIDO','PAD')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(33,'BAIXAO','BAIX')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(34,'GROTA','GROT')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(35,'LINHA','LINH')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(36,'ILHA','ILHA')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(37,'FAVELA','FAVE')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(38,'CORTICO','COT')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(39,'MORRO','MORR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(40,'LAGOA','LAGO')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(41,'ESTRADA','ESTR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(42,'PORTO','PORT')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(43,'AREA DE ABRANGENCIA','ABRG')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(44,'RUA','RUA')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(45,'AVENIDA','AV')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(46,'SETOR CENSITARIO','SCEN')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(47,'NUMERO','NR')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(48,'LOTE','LT')
;
INSERT INTO DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE
(co_seq_categoria,no_categoria,sg_categoria)
VALUES
(49,'BECO','BC')
;
COMMIT;
