INSERT INTO dblocalidade.tb_naturalidade
VALUES
(1,'IGNORADO',0)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(2,'BRASIL',1)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(3,'ARGENTINA',11)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(4,'BOLIVIA',12)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(5,'PARAGUAI',13)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(6,'URUGUAI',14)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(7,'AMERICA DO SUL (OUTROS)',10)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(8,'AMERICA CENTRAL',20)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(9,'CARIBE',30)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(10,'ESTADOS UNIDOS',41)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(11,'AMERICA DO NORTE (OUTROS)',40)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(12,'ILHAS BRITANICAS',50)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(13,'EUROPA NORDICA',60)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(14,'ALEMANHA OC',71)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(15,'ALEMANHA OR',72)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(16,'AUSTRIA',73)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(17,'ESPANHA',74)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(18,'FRANCA',75)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(19,'ITALIA',76)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(20,'PORTUGAL',77)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(21,'SUICA',78)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(22,'EUROPA OCIDENTAL (OUTROS)',70)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(23,'HUNGRIA',81)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(24,'IUGOSLAVIA',82)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(25,'POLONIA',83)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(26,'EUROPA ORIENTAL (OUTROS)',80)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(27,'AFRICA SETENTRIONAL',90)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(28,'AFRICA CENTRAL',100)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(29,'AFRICA MERIDIONAL',110)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(30,'LIBANO',121)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(31,'SIRIA',122)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(32,'ASIA OCIDENTAL (OUTROS)',120)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(33,'ASIA CENTRAL',130)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(34,'ASIA MERIDIONAL',140)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(35,'CHINA',151)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(36,'JAPAO',152)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(37,'ASIA ORIENTAL (OUTROS)',150)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(38,'OCEANIA',160)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(39,'EX-URSS',170)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(40,'RONDONIA',811)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(41,'ACRE',812)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(42,'AMAZONAS',813)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(43,'RORAIMA',814)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(44,'PARA',815)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(45,'AMAPA',816)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(46,'TOCANTINS',817)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(47,'MARANHAO',821)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(48,'PIAUI',822)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(49,'CEARA',823)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(50,'RIO GRANDE DO NORTE',824)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(51,'PARAIBA',825)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(52,'PERNAMBUCO',826)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(53,'ALAGOAS',827)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(54,'SERGIPE',828)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(55,'BAHIA',829)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(56,'MINAS GERAIS',831)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(57,'ESPIRITO SANTO',832)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(58,'RIO DE JANEIRO',833)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(59,'SAO PAULO',835)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(60,'PARANA',841)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(61,'SANTA CATARINA',842)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(62,'RIO GRANDE DO SUL',843)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(63,'MATO GROSSO DO SUL',850)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(64,'MATO GROSSO',851)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(65,'GOIAS',852)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(66,'DISTRITO FEDERAL',853)
;
INSERT INTO dblocalidade.tb_naturalidade
VALUES
(67,'IGNORADO',999)
;
