CREATE TABLE DBLOCALIDADE.RL_REGIONAL_MUNICIPIO_SVS (
CO_REGIONAL          NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_REGIONAL_COREGIONAL CHECK (CO_REGIONAL IS NOT NULL),
CO_SISTEMA           NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_REGIONAL_COSISTEMA CHECK (CO_SISTEMA IS NOT NULL),
CO_UF_IBGE           VARCHAR(2)           NOT NULL 
      CONSTRAINT NN_REGIONAL_COUFIBGE CHECK (CO_UF_IBGE IS NOT NULL),
CO_MUNICIPIO_IBGE    VARCHAR(6)           NOT NULL 
      CONSTRAINT NN_REGIONAL_COMUNICIPIOIBGE CHECK (CO_MUNICIPIO_IBGE IS NOT NULL),
CO_MUNICIPIO_SVS     NUMERIC(6)           NULL,
CONSTRAINT PK_REGIONAL_MUNICIPIO_SVS PRIMARY KEY (CO_REGIONAL, CO_SISTEMA, CO_UF_IBGE, CO_MUNICIPIO_IBGE)
);



CREATE TABLE DBLOCALIDADE.TB_CARTORIO (
CO_CARTORIO          NUMERIC(8,0)         NOT NULL 
      CONSTRAINT NN_CARTORIO_COCARTORIO CHECK (CO_CARTORIO  IS NOT NULL),
DS_CARTORIO          VARCHAR(100)          NULL,
CO_MUNICIPIO_IBGE    VARCHAR(6)           NULL,
ST_REGISTRO_ATIVO    VARCHAR(1)           NULL,
DT_CADASTRO          DATE                 NULL,
CONSTRAINT PK_CARTORIO PRIMARY KEY (CO_CARTORIO)
);

CREATE TABLE DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE (
CO_SEQ_CATEGORIA     NUMERIC(4)           NOT NULL 
      CONSTRAINT NN_CATEGLOCALIDADE_COSEQCATEG CHECK (CO_SEQ_CATEGORIA IS NOT NULL),
NO_CATEGORIA         VARCHAR(30)          NOT NULL 
      CONSTRAINT NN_CATEGLOCALIDADE_NOCATEGORIA CHECK (NO_CATEGORIA IS NOT NULL),
SG_CATEGORIA         VARCHAR(6)           NULL,
CONSTRAINT PK_CATEGORIA_LOCALIDADE PRIMARY KEY (CO_SEQ_CATEGORIA)
);

CREATE UNIQUE INDEX IN_CATEGLOCAL_COSEQCATEGORIA ON DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE (
CO_SEQ_CATEGORIA
);

CREATE TABLE DBLOCALIDADE.TB_ESTABELECIMENTO_SAUDE (
CO_ESTABELECIMENTO   NUMERIC(8,0)         NOT NULL 
      CONSTRAINT NN_ESTABSAUDE_COESTAB CHECK (CO_ESTABELECIMENTO IS NOT NULL),
CO_MUNICIPIO_IBGE    VARCHAR(6)           NOT NULL 
      CONSTRAINT NN_ESTABSAUDE_COMUNICIPIOIBGE CHECK (CO_MUNICIPIO_IBGE IS NOT NULL),
DS_ESTABELECIMENTO   VARCHAR(100)          NULL,
DS_BAIRRO_ESTABELECIMENTO VARCHAR(100)         NULL,
DS_ENDERECO_ESTABELECIMENTO VARCHAR(100)         NULL,
DS_COMPLEMENTO_ESTABELECIMENTO VARCHAR(100)         NULL,
ST_REGISTRO_ATIVO    VARCHAR(1)           NULL,
NU_CEP_ESTABELECIMENTO VARCHAR(10)          NULL,
CO_CNES              VARCHAR(7)           NULL,
NU_FAX_ESTABELECIMENTO VARCHAR(13)          NULL,
DS_EMAIL_ESTABELECIMENTO VARCHAR(60)          NULL,
TP_UNIDADE           VARCHAR(2)           NULL,
NU_FONE_ESTABELECIMENTO VARCHAR(13)          NULL,
ST_DIGITACAO         VARCHAR(1)           NULL,
NO_RAZAO_SOCIAL      VARCHAR(70)          NULL,
NU_ENDERECO_ESTABELECIMENTO VARCHAR(20)          NULL,
DT_CADASTRO             DATE                    NULL,       --ADICIONADO
NU_CNPJ_ESTABELECIMENTO VARCHAR(14)          NULL,    --ADICIONADO
CONSTRAINT PK_ESTABELECIMENTO_SAUDE PRIMARY KEY (CO_ESTABELECIMENTO, CO_MUNICIPIO_IBGE)
);

CREATE TABLE DBLOCALIDADE.TB_ESTATISTICA_IBGE (
CO_UF_MUNICIPIO_IBGE VARCHAR(6)           NOT NULL 
      CONSTRAINT NN_ESTATISTICAIBGE_COUFMUNIC CHECK (CO_UF_MUNICIPIO_IBGE IS NOT NULL),
NU_ANO               VARCHAR(4)           NOT NULL 
      CONSTRAINT NN_ESTATISTICAIBGE_NUANO CHECK (NU_ANO IS NOT NULL),
NU_POPTOTAL          NUMERIC(10)          NULL,
NU_POPTOTAL_M        NUMERIC(10)          NULL,
NU_POPTOTAL_F        NUMERIC(10)          NULL,
NU_POP1ANO           NUMERIC(10)          NULL,
NU_POP1ANO_M         NUMERIC(10)          NULL,
NU_POP1ANO_F         NUMERIC(10)          NULL,
NU_POP1A4ANOS        NUMERIC(10)          NULL,
NU_POP1A4ANOS_M      NUMERIC(10)          NULL,
NU_POP1A4ANOS_F      NUMERIC(10)          NULL,
NU_POP5A9ANOS        NUMERIC(10)          NULL,
NU_POP5A9ANOS_M      NUMERIC(10)          NULL,
NU_POP5A9ANOS_F      NUMERIC(10)          NULL,
NU_POP10A14ANOS      NUMERIC(10)          NULL,
NU_POP10A14ANOS_M    NUMERIC(10)          NULL,
NU_POP10A14ANOS_F    NUMERIC(10)          NULL,
NU_POP15A19ANOS      NUMERIC(10)          NULL,
NU_POP15A19ANOS_M    NUMERIC(10)          NULL,
NU_POP15A19ANOS_F    NUMERIC(10)          NULL,
NU_POP20A29ANOS      NUMERIC(10)          NULL,
NU_POP20A29ANOS_M    NUMERIC(10)          NULL,
NU_POP20A29ANOS_F    NUMERIC(10)          NULL,
NU_POP30A39ANOS      NUMERIC(10)          NULL,
NU_POP30A39ANOS_M    NUMERIC(10)          NULL,
NU_POP30A39ANOS_F    NUMERIC(10)          NULL,
NU_POP40A49ANOS      NUMERIC(10)          NULL,
NU_POP40A49ANOS_M    NUMERIC(10)          NULL,
NU_POP40A49ANOS_F    NUMERIC(10)          NULL,
NU_POP50A59ANOS      NUMERIC(10)          NULL,
NU_POP50A59ANOS_M    NUMERIC(10)          NULL,
NU_POP50A59ANOS_F    NUMERIC(10)          NULL,
NU_POP60A69ANOS      NUMERIC(10)          NULL,
NU_POP60A69ANOS_M    NUMERIC(10)          NULL,
NU_POP60A69ANOS_F    NUMERIC(10)          NULL,
NU_POP70A79ANOS      NUMERIC(10)          NULL,
NU_POP70A79ANOS_M    NUMERIC(10)          NULL,
NU_POP70A79ANOS_F    NUMERIC(10)          NULL,
NU_POP80             NUMERIC(10)          NULL,
NU_POP80_M           NUMERIC(10)          NULL,
NU_POP80_F           NUMERIC(10)          NULL,
NU_POPIDADE_IGN      NUMERIC(10)          NULL,
NU_POPIDADE_IGN_M    NUMERIC(10)          NULL,
NU_POPIDADE_IGN_F    NUMERIC(10)          NULL,
NU_HAB_DOMIC         NUMERIC(10)          NULL,
NU_HAB_DOMIC_M       NUMERIC(10)          NULL,
NU_HAB_DOMIC_F       NUMERIC(10)          NULL,
NU_GESTANTE          NUMERIC(10)          NULL,
NU_NASC_VIVOS        NUMERIC(10)          NULL,
NU_NASC_VIVOS_M      NUMERIC(10)          NULL,
NU_NASC_VIVOS_F      NUMERIC(10)          NULL,
NU_NASC_MORTOS       NUMERIC(10)          NULL,
NU_NASC_MORTOS_M     NUMERIC(10)          NULL,
NU_NASC_MORTOS_F     NUMERIC(10)          NULL,
NU_OBITOS            NUMERIC(10)          NULL,
NU_OBITOS_M          NUMERIC(10)          NULL,
NU_OBITOS_F          NUMERIC(10)          NULL,
ST_INF_ATUAL         VARCHAR(1)           NULL,
CO_ESTADO_MUNICIPIO  NUMERIC(6)           NULL,
ST_UF_MUNICIPIO      VARCHAR(1)           NULL,
CONSTRAINT PK_ESTATISTICA_IBGE_MUNICIPIO PRIMARY KEY (CO_UF_MUNICIPIO_IBGE, NU_ANO)
);

CREATE UNIQUE INDEX IX_ESTAT_IBGE_MUNICIPIO ON DBLOCALIDADE.TB_ESTATISTICA_IBGE (
CO_UF_MUNICIPIO_IBGE,
NU_ANO
);


CREATE TABLE DBLOCALIDADE.TB_DISTRITO_SVS  (
   CO_DISTRITO          VARCHAR(9)                      NOT NULL
      CONSTRAINT NN_DISTRITO_CODISTRITO CHECK (CO_DISTRITO IS NOT NULL),
   NO_DISTRITO          VARCHAR(50),
   CO_MUNICIPIO_IBGE    VARCHAR(6),
   CO_SISTEMA           NUMERIC(8)                      
      CONSTRAINT CKC_CO_SISTEMA_TB_DISTR CHECK (CO_SISTEMA IS NULL OR (CO_SISTEMA IS NOT NULL)),
   ST_REGISTRO_ATIVO    VARCHAR(1),
   CONSTRAINT PK_DISTRITO_SVS PRIMARY KEY (CO_DISTRITO),
   CONSTRAINT NN_DISTRITOSVS_CODISTRITO CHECK (CO_DISTRITO IS NOT NULL)
);

COMMENT ON TABLE DBLOCALIDADE.TB_DISTRITO_SVS IS
'Contém informações sobre distritos sanitários';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_DISTRITO IS
'Código IBGE do Distrito Sanitário';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.NO_DISTRITO IS
'Nome do Distrito Sanitário';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_MUNICIPIO_IBGE IS
'Código IBGE do Município';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.CO_SISTEMA IS
'Código Sequencial do Sistema';

COMMENT ON COLUMN DBLOCALIDADE.TB_DISTRITO_SVS.ST_REGISTRO_ATIVO IS
'Indica se o registro está ativo';


CREATE TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO  (
   CO_ESTABELECIMENTO   NUMERIC(8,0)                     NOT NULL
      CONSTRAINT CKC_CO_ESTABELECIMENT_RL_ESTAB CHECK (CO_ESTABELECIMENTO IS NOT NULL),
   CO_MUNICIPIO_IBGE    VARCHAR(6)                     NOT NULL
      CONSTRAINT CKC_CO_MUNICIPIO_IBGE_RL_ESTAB CHECK (CO_MUNICIPIO_IBGE IS NOT NULL),
   CO_DISTRITO          VARCHAR(9)                      NOT NULL,
   CO_SISTEMA           NUMERIC(8)                      NOT NULL,
   CONSTRAINT PK_ESTAB_SAUDE_DISTRITO PRIMARY KEY (CO_ESTABELECIMENTO, CO_MUNICIPIO_IBGE, CO_DISTRITO, CO_SISTEMA)
);

COMMENT ON TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO IS
'RL_ESTAB_SAUDE_DISTRITO';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_ESTABELECIMENTO IS
'Código do Estabelecimento de Saúde';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_MUNICIPIO_IBGE IS
'Código do Município IBGE';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_DISTRITO IS
'Código IBGE do Distrito';

COMMENT ON COLUMN DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO.CO_SISTEMA IS
'Código do Sistema';


CREATE TABLE DBLOCALIDADE.TB_LOCALIDADE (
CO_SEQ_LOCALIDADE    NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_LOCALIDADE_COSEQLOCAL CHECK (CO_SEQ_LOCALIDADE IS NOT NULL),
CO_SISTEMA           NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_LOCALIDADE_COSISTEMA CHECK (CO_SISTEMA IS NOT NULL),
CO_CATEGORIA         NUMERIC(4)           NOT NULL 
      CONSTRAINT NN_LOCALIDADE_COCATEGORIA CHECK (CO_CATEGORIA IS NOT NULL),
CO_ESTADO_SVS        NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_LOCALIDADE_COESTADOSVS CHECK (CO_ESTADO_SVS IS NOT NULL),
CO_MUNICIPIO_SVS     NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_LOCALIDADE_COMUNICIPIOSVS CHECK (CO_MUNICIPIO_SVS IS NOT NULL),
NU_LOCALIDADE        VARCHAR(15)          NULL,
CO_DISTRITO_SVS      NUMERIC(8)           NULL,
CO_UF_IBGE           VARCHAR(2)           NULL,
CO_DISTRITO          VARCHAR(9)           NULL,
CO_MUNICIPIO_IBGE    VARCHAR(6)           NULL,
NO_LOCALIDADE        VARCHAR(100)         NULL,
TP_ZONA              VARCHAR(1)           NULL,
ST_LOCALIDADE        VARCHAR(1)           NULL,
QT_PREDIO            NUMERIC(8)           NULL,
QT_HABITANTE         NUMERIC(8)           NULL,
NU_CROQ              NUMERIC(8)           NULL,
NU_CEP               VARCHAR(8)           NULL,
NU_LONGITUDE         NUMERIC(10,8)        NULL,
NU_LATITUDE          NUMERIC(10,8)        NULL,
NU_ALTITUDE          NUMERIC(5,1)         NULL,
DT_INCLUSAO_REG      DATE                 NULL,
DT_ALTERACAO_REG     DATE                 NULL,
NU_CENSITARIO        NUMERIC(5)           NULL,
NU_REGIONAL          NUMERIC(4)           NULL,
NU_REGIAO_ZONA       NUMERIC(4)           NULL,
CO_LOCALIDADE_BAIRRO NUMERIC(8)           NULL,
CO_SISTEMA_BAIRRO    NUMERIC(8)           NULL,
CONSTRAINT PK_LOCALIDADE PRIMARY KEY (CO_SEQ_LOCALIDADE, CO_SISTEMA)
);

CREATE  INDEX IN_LOCALIDADE_COSEQLOCALIDADE ON DBLOCALIDADE.TB_LOCALIDADE (
CO_SEQ_LOCALIDADE
);

CREATE TABLE DBLOCALIDADE.TB_NATURALIDADE (
CO_NATURALIDADE      NUMERIC(2,0)         NOT NULL 
      CONSTRAINT NN_NATURALIDADE_CONATURALIDADE CHECK (CO_NATURALIDADE IS NOT NULL),
DS_NATURALIDADE      VARCHAR(30)          NULL,
NU_NATURALIDADE      NUMERIC(3,0)         NULL,
CONSTRAINT PK_NATURALIDADE PRIMARY KEY (CO_NATURALIDADE)
);

CREATE TABLE DBLOCALIDADE.TB_OCUPACAO (
CO_OCUPACAO          NUMERIC(8,0)         NOT NULL 
      CONSTRAINT NN_OCUPACAO_COOCUPACAO CHECK (CO_OCUPACAO IS NOT NULL),
DS_OCUPACAO          VARCHAR(120)          NOT NULL 
      CONSTRAINT NN_OCUPACAO_DSOCUPACAO CHECK (DS_OCUPACAO IS NOT NULL),
CO_CBO               VARCHAR(6)           NULL,
TP_ESCOLARIDADE      VARCHAR(1)           NULL,
ST_RESTRICAO_IDADE   VARCHAR(2)           NULL,
CONSTRAINT PK_OCUPACAO PRIMARY KEY (CO_OCUPACAO)
);


CREATE TABLE DBLOCALIDADE.TB_REGIONAL_SVS (
CO_SEQ_REGIONAL      NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_REGIONALSVS_COSEQREGIONAL CHECK (CO_SEQ_REGIONAL IS NOT NULL),
CO_SISTEMA           NUMERIC(8)           NOT NULL 
      CONSTRAINT NN_REGIONALSVS_COSEQSISTEMA CHECK (CO_SISTEMA IS NOT NULL),
CO_UF_IBGE           VARCHAR(2)           NOT NULL 
      CONSTRAINT NN_REGIONALSVS_COUFIBGE CHECK (CO_UF_IBGE IS NOT NULL),
CO_ESTADO_SVS        NUMERIC(4)           NULL,
NO_REGIONAL          VARCHAR(50)          NULL,
CONSTRAINT PK_REGIONAL_SVS PRIMARY KEY (CO_SEQ_REGIONAL, CO_SISTEMA, CO_UF_IBGE)
);


ALTER TABLE DBLOCALIDADE.RL_REGIONAL_MUNICIPIO_SVS
   ADD CONSTRAINT FK_REGIONALMUNICIPIO_MUNICIPIO FOREIGN KEY (CO_MUNICIPIO_IBGE)
      REFERENCES DBGERAL.TB_MUNICIPIO (CO_MUNICIPIO_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.RL_REGIONAL_MUNICIPIO_SVS
   ADD CONSTRAINT FK_REGIONALMUNICIPIO_REGIONAL FOREIGN KEY (CO_REGIONAL, CO_SISTEMA, CO_UF_IBGE)
      REFERENCES DBLOCALIDADE.TB_REGIONAL_SVS (CO_SEQ_REGIONAL, CO_SISTEMA, CO_UF_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_CARTORIO
   ADD CONSTRAINT FK_CARTORIO_MUNICIPIO FOREIGN KEY (CO_MUNICIPIO_IBGE)
      REFERENCES DBGERAL.TB_MUNICIPIO (CO_MUNICIPIO_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_ESTABELECIMENTO_SAUDE
   ADD CONSTRAINT FK_ESTABSAUDE_MUNICIPIO FOREIGN KEY (CO_MUNICIPIO_IBGE)
      REFERENCES DBGERAL.TB_MUNICIPIO (CO_MUNICIPIO_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_CATEGORIALOCAL FOREIGN KEY (CO_CATEGORIA)
      REFERENCES DBLOCALIDADE.TB_CATEGORIA_LOCALIDADE (CO_SEQ_CATEGORIA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_DISTRITO FOREIGN KEY (CO_DISTRITO)
      REFERENCES DBLOCALIDADE.TB_DISTRITO_SVS (CO_DISTRITO)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_MUNICIPIO FOREIGN KEY (CO_MUNICIPIO_IBGE)
      REFERENCES DBGERAL.TB_MUNICIPIO (CO_MUNICIPIO_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_SISTEMA FOREIGN KEY (CO_SISTEMA)
      REFERENCES DBCSPU.TB_SISTEMA (CO_SEQ_SISTEMA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_UF FOREIGN KEY (CO_UF_IBGE)
      REFERENCES DBGERAL.TB_UF (CO_UF_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_REGIONAL_SVS
   ADD CONSTRAINT FK_REGIONALSVS_SISTEMA FOREIGN KEY (CO_SISTEMA)
      REFERENCES DBCSPU.TB_SISTEMA (CO_SEQ_SISTEMA)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_REGIONAL_SVS
   ADD CONSTRAINT FK_REGIONALSVS_UF FOREIGN KEY (CO_UF_IBGE)
      REFERENCES DBGERAL.TB_UF (CO_UF_IBGE)
      ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE DBLOCALIDADE.TB_LOCALIDADE
   ADD CONSTRAINT FK_LOCALIDADE_LOCALIDADE FOREIGN KEY (CO_LOCALIDADE_BAIRRO, CO_SISTEMA_BAIRRO)
      REFERENCES DBLOCALIDADE.TB_LOCALIDADE (CO_SEQ_LOCALIDADE, CO_SISTEMA);

ALTER TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO
   ADD CONSTRAINT FK_DISTRITO_ESTABSAUDEDIST FOREIGN KEY (CO_DISTRITO)
      REFERENCES DBLOCALIDADE.TB_DISTRITO_SVS (CO_DISTRITO);

ALTER TABLE DBLOCALIDADE.RL_ESTAB_SAUDE_DISTRITO
   ADD CONSTRAINT FK_ESTABSAUDE_ESTABSAUDEDIST FOREIGN KEY (CO_ESTABELECIMENTO, CO_MUNICIPIO_IBGE)
      REFERENCES DBLOCALIDADE.TB_ESTABELECIMENTO_SAUDE (CO_ESTABELECIMENTO, CO_MUNICIPIO_IBGE);

ALTER TABLE DBLOCALIDADE.TB_DISTRITO_SVS
   ADD CONSTRAINT FK_SISTEMA_DISTRITOSVS FOREIGN KEY (CO_SISTEMA)
      REFERENCES DBCSPU.TB_SISTEMA (CO_SEQ_SISTEMA);
